"""Cover observable package CLI behavior across configuration and installation.

Temporary package trees, TOML parsing, and filesystem output are real. Windows
registry, junction, shortcut, process, and network boundaries are mocked where
the behavior would otherwise depend on the host. Internal module layout and
private call order are out of scope.
"""

from __future__ import annotations

import contextlib
import hashlib
import importlib.util
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import tomllib
import urllib.request
import zipfile
from pathlib import Path
from types import ModuleType
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ROOT / "src"
GUPKG_PY = SRC_ROOT / "gupkg" / "gupkg.py"
FIXTURES = ROOT / "tests" / "fixtures"


def load_gupkg_module():
    spec = importlib.util.spec_from_file_location("gupkg_under_test_cli", GUPKG_PY)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(spec.name, None)
    return module


def runtime_module(name: str) -> ModuleType:
    """Return one runtime module loaded by the ``gupkg.py`` entrypoint."""

    return sys.modules[f"gupkg.{name}"]


@contextlib.contextmanager
def pushd(path: Path):
    cwd = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(cwd)


class GupkgCliBehaviorTests(unittest.TestCase):
    maxDiff = None

    def run_main(self, module, args: list[str]) -> tuple[int, str]:
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            try:
                code = module.main(args)
            except SystemExit as exc:
                code = exc.code
        if code is None:
            code = 0
        self.assertIsInstance(code, int)
        return code, stdout.getvalue()

    def user_env(self, tmpdir: str) -> dict[str, str]:
        root = Path(tmpdir)
        return {
            "APPDATA": str(root / "AppData"),
            "USERPROFILE": str(root / "UserProfile"),
        }

    def machine_env(self, tmpdir: str) -> dict[str, str]:
        root = Path(tmpdir)
        return {
            "PROGRAMDATA": str(root / "ProgramData"),
            "SYSTEMDRIVE": str(root / "SystemDrive"),
        }

    def copy_fixture(self, tmpdir: str, name: str) -> Path:
        destination = Path(tmpdir) / name
        shutil.copytree(FIXTURES / name, destination)
        return destination

    def make_version_dir(
        self, tmpdir: str, package: str, version_dir_name: str = "v1.0.0.l1"
    ) -> Path:
        version_dir = Path(tmpdir) / package / version_dir_name
        version_dir.mkdir(parents=True)
        return version_dir

    def write_config(self, version_dir: Path, text: str) -> None:
        version_dir.joinpath("pkg.toml").write_text(
            textwrap.dedent(text).lstrip(), encoding="utf-8"
        )

    def zip_bytes(self, entries: dict[str, str]) -> bytes:
        archive = io.BytesIO()
        with zipfile.ZipFile(archive, "w") as zip_file:
            for name, content in entries.items():
                zip_file.writestr(name, content)
        return archive.getvalue()

    def run_git(self, cwd: Path, *args: str) -> None:
        """Run one Git command for a local repository fixture."""
        subprocess.run(
            ["git", *args],
            cwd=cwd,
            check=True,
            capture_output=True,
            text=True,
        )

    def assert_documented_starter_config(
        self,
        text: str,
        *,
        name: str,
        version: str,
        local_version: int,
        only_portable: bool = False,
    ) -> None:
        nonblank_lines = [line.strip() for line in text.splitlines() if line.strip()]
        self.assertTrue(nonblank_lines, msg="Starter config should not be empty.")
        header = nonblank_lines[0]
        self.assertTrue(
            header.startswith("#"),
            msg="Starter config should begin with a comment header.",
        )
        self.assertIn(
            "gupkg",
            header.lower(),
            msg="Starter config header should identify gupkg as the generator.",
        )
        self.assertTrue(
            any(
                token in header.lower()
                for token in ("generated", "auto-generated", "autogenerated")
            ),
            msg="Starter config header should indicate that the file was generated.",
        )
        self.assertIn(f'name = "{name}"', text)
        self.assertIn(f'version = "{version}"', text)
        self.assertIn(f"localVersion = {local_version}", text)
        self.assertIn(f"only_portable = {str(only_portable).lower()}", text)
        self.assertIn("# [origin]", text)
        self.assertIn("# [[origin.versions]]", text)
        self.assertIn("# Multiple origin versions:", text)
        self.assertIn("#   1. omit top-level url/script above", text)
        self.assertIn(
            "# Or use the package top-level version to select the current origin:", text
        )
        self.assertIn(
            "#   2. define a [[origin.versions]] entry whose version matches", text
        )
        self.assertIn("#      the top-level package version above", text)
        for example_block in ("shortcut", "environment", "path", "bin"):
            self.assertIn(f"# [[{example_block}]]", text)

    def test_version_flag_reports_version(self) -> None:
        """Version flag reports version."""
        module = load_gupkg_module()
        code, output = self.run_main(module, ["--version"])
        self.assertEqual(code, 0)
        self.assertIn(module.__version__, output)

    def test_tui_command_delegates_to_the_textual_entrypoint(self) -> None:
        """The tui command starts the optional interactive entrypoint."""
        module = load_gupkg_module()
        tui = ModuleType("gupkg.tui")
        tui.run_tui = mock.Mock(return_value=0)

        with (
            mock.patch.dict(sys.modules, {"gupkg.tui": tui}),
            mock.patch("gupkg.dependencies.ensure_runtime_dependencies"),
        ):
            code, _ = self.run_main(module, ["tui"])

        self.assertEqual(code, 0)
        tui.run_tui.assert_called_once_with()

    def test_tui_provisions_its_declared_runtime_dependencies(self) -> None:
        """The tui command provisions its gupkg-owned dependencies before launch."""
        module = load_gupkg_module()
        tui = ModuleType("gupkg.tui")
        tui.run_tui = mock.Mock(return_value=0)

        with (
            mock.patch.dict(sys.modules, {"gupkg.tui": tui}),
            mock.patch(
                "gupkg.dependencies.ensure_runtime_dependencies"
            ) as ensure_dependencies,
        ):
            code, _ = self.run_main(module, ["tui"])

        self.assertEqual(code, 0)
        ensure_dependencies.assert_called_once_with("tui")
        tui.run_tui.assert_called_once_with()

    def test_short_help_hides_bootstrap_and_removed_flags(self) -> None:
        """Short help hides bootstrap and removed flags."""
        module = load_gupkg_module()
        code, help_text = self.run_main(module, ["--help"])
        self.assertEqual(code, 0)
        self.assertNotIn("--action", help_text)
        self.assertNotIn("--fix-config", help_text)
        self.assertNotIn("--force", help_text)
        self.assertIn("--allow-downgrade", help_text)
        self.assertNotIn("--python", help_text)
        self.assertNotIn("--no-autoupdate-config", help_text)
        self.assertNotIn("Compress", help_text)

    def test_invalid_install_path_returns_user_error_and_banner(self) -> None:
        """Invalid install path returns user error and banner."""
        module = load_gupkg_module()
        code, output = self.run_main(
            module, ["install", str(ROOT / "does-not-exist")]
        )
        self.assertEqual(code, module.EXIT_USER_ERROR)
        self.assertIn("Operation: install", output)
        self.assertIn("install failed.", output)

    def test_update_check_accepts_historical_version_without_current(self) -> None:
        """Update checks use an explicitly selected historical version without current."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            upstream = root / "upstream"
            upstream.mkdir()
            self.run_git(upstream, "init")
            self.run_git(upstream, "checkout", "-b", "main")
            self.run_git(upstream, "config", "user.name", "Gupkg Tests")
            self.run_git(upstream, "config", "user.email", "gupkg-tests@example.invalid")
            upstream.joinpath("payload.txt").write_text("one", encoding="utf-8")
            self.run_git(upstream, "add", "payload.txt")
            self.run_git(upstream, "commit", "-m", "initial")

            package_root = root / "HistoricalApp"
            version_dir = package_root / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            subprocess.run(
                ["git", "clone", str(upstream), str(version_dir / "App")],
                check=True,
                capture_output=True,
                text=True,
            )
            self.write_config(
                version_dir,
                f"""
                name = "HistoricalApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                mode = "git"
                url = "{upstream.as_posix()}"

                [update]

                [update.payload]
                mode = "git"
                """,
            )
            upstream.joinpath("payload.txt").write_text("two", encoding="utf-8")
            self.run_git(upstream, "add", "payload.txt")
            self.run_git(upstream, "commit", "-m", "update")

            code, output = self.run_main(
                module,
                ["upgrade", "check", str(version_dir)],
            )

        self.assertEqual(code, module.EXIT_SUCCESS)
        self.assertIn("Available: v", output)

    def test_config_check_rejects_removed_automatic_update_setting(self) -> None:
        """Config check rejects the removed automatic-update setting."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ManualUpdates")
            self.write_config(
                version_dir,
                """
                name = "ManualUpdates"
                version = "1.0.0"
                localVersion = 1

                [update]
                allow_automatic_update = true

                [update.check]
                mode = "module"

                [update.payload]
                mode = "zip"
                """,
            )

            code, output = self.run_main(
                module, ["config", "check", str(version_dir)]
            )

        self.assertEqual(code, module.EXIT_USER_ERROR)
        self.assertIn("Unknown key 'allow_automatic_update' in update", output)

    def test_bootstrap_git_install_creates_populated_timestamped_version(self) -> None:
        """Installing bootstrap-git promotes its origin into an immutable version."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            upstream = root / "upstream"
            upstream.mkdir()

            # Build one upstream commit for the bootstrap template to resolve
            # without first populating the template's own App directory.
            self.run_git(upstream, "init")
            self.run_git(upstream, "checkout", "-b", "main")
            self.run_git(upstream, "config", "user.name", "Gupkg Tests")
            self.run_git(
                upstream, "config", "user.email", "gupkg-tests@example.invalid"
            )
            upstream.joinpath("payload.txt").write_text("one", encoding="utf-8")
            self.run_git(upstream, "add", "payload.txt")
            self.run_git(upstream, "commit", "-m", "initial")

            package_root = root / "ImmutableGitApp"
            version_dir = package_root / "vbootstrap-git.l2"
            version_dir.mkdir(parents=True)
            self.write_config(
                version_dir,
                f"""
                name = "ImmutableGitApp"
                version = "bootstrap-git"
                localVersion = 2

                [origin]
                mode = "git"
                url = "{upstream.as_posix()}"

                [update]

                [update.payload]
                mode = "git"
                """,
            )

            # Upgrade checks can inspect a bootstrap template directly without
            # populating App or requiring a current junction.
            check_code, check_output = self.run_main(
                module, ["--toml", "upgrade", "check", str(version_dir)]
            )
            self.assertEqual(check_code, module.EXIT_SUCCESS)
            self.assertIn("Available: v", check_output)
            self.assertIn('status = "available"', check_output)
            self.assertIn(
                "Upgrade is available. Run 'gupkg upgrade download' to stage it; "
                "this check did not change any files.",
                check_output,
            )
            self.assertNotIn("no changes needed", check_output)
            self.assertFalse((version_dir / "App").exists())

            # Installing the bootstrap template must stage and install a new
            # immutable .l1 version rather than activating bootstrap-git itself.
            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    result = module.install_package(version_dir)

            new_versions = [
                path
                for path in package_root.glob("v*.l*")
                if path != version_dir
            ]
            self.assertTrue(result.ok, msg=result.errors)
            self.assertTrue(result.changed)
            self.assertEqual(len(new_versions), 1)

            new_version = new_versions[0]
            self.assertRegex(
                new_version.name,
                re.compile(r"^v\d{8}-\d{6}-git\.l1$"),
            )
            new_config = tomllib.loads(
                (new_version / "pkg.toml").read_text(encoding="utf-8")
            )
            self.assertEqual(new_config["name"], "ImmutableGitApp")
            self.assertEqual(
                new_config["version"], new_version.name[1:].rsplit(".l", 1)[0]
            )
            self.assertEqual(new_config["localVersion"], 1)
            self.assertEqual(new_config["update"]["payload"]["mode"], "git")
            self.assertEqual(
                (new_version / "App" / "payload.txt").read_text(encoding="utf-8"),
                "one",
            )
            self.assertTrue((new_version / "App" / ".git").is_dir())
            self.assertFalse((version_dir / "App").exists())

            # Reinstalling the same bootstrap must reuse its original .l1
            # promotion instead of creating an otherwise identical .l2.
            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    repeat_result = module.install_package(version_dir)

            concrete_versions = [
                path for path in package_root.glob("v*.l*") if path != version_dir
            ]
            self.assertTrue(repeat_result.ok, msg=repeat_result.errors)
            self.assertEqual(concrete_versions, [new_version])
            self.assertTrue(new_version.name.endswith(".l1"))

            # A wrapper launched inside the active concrete version defaults
            # its path to ".". Accept that active version while retaining the
            # historical-version safety rule.
            upstream.joinpath("payload.txt").write_text("two", encoding="utf-8")
            self.run_git(upstream, "add", "payload.txt")
            self.run_git(upstream, "commit", "-m", "update")
            current = package_root / "current"
            current.mkdir()
            layout = runtime_module("layout")
            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(layout, "is_junction", return_value=True):
                    with mock.patch.object(
                        layout, "get_junction_target", return_value=new_version
                    ):
                        with mock.patch.object(
                            module,
                            "update_current_junction_if_needed",
                            return_value=True,
                        ):
                            update_result = module.full_package_upgrade(
                                new_version, scope=module.Scope.USER
                            )

            updated_versions = [
                path
                for path in package_root.glob("v*.l*")
                if path not in {version_dir, new_version}
            ]
            self.assertTrue(update_result.ok, msg=update_result.errors)
            self.assertEqual(update_result.status, "installed-update")
            self.assertEqual(len(updated_versions), 1)
            self.assertEqual(
                (updated_versions[0] / "App" / "payload.txt").read_text(
                    encoding="utf-8"
                ),
                "two",
            )

    def test_upgrade_install_rejects_a_receipt_for_the_active_version(self) -> None:
        """Upgrade install requires a staged version newer than the active version."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ReceiptApp")
            receipts = version_dir.parent / ".gupkg" / "receipts"
            receipts.mkdir(parents=True)
            receipts.joinpath("v1.0.0.l1.toml").write_text(
                "schemaVersion = 1\nversion = \"1.0.0\"\nlocalVersion = 1\n",
                encoding="utf-8",
            )

            result = module.install_downloaded_update(version_dir)

        self.assertFalse(result.ok)
        self.assertEqual(result.exit_code, module.EXIT_USER_ERROR)
        self.assertEqual(
            result.errors,
            [
                "No downloaded upgrade is waiting to be installed. Run "
                "'gupkg upgrade download' first."
            ],
        )

    def test_upgrade_install_rejects_a_receipt_older_than_an_installed_version(self) -> None:
        """Upgrade install does not replace a newer installed version."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ReceiptApp")
            newer_version = version_dir.parent / "v3.0.0.l1"
            newer_version.mkdir()
            receipts = version_dir.parent / ".gupkg" / "receipts"
            receipts.mkdir(parents=True)
            receipts.joinpath("v2.0.0.l1.toml").write_text(
                "schemaVersion = 1\nversion = \"2.0.0\"\nlocalVersion = 1\n",
                encoding="utf-8",
            )
            (version_dir.parent / "v2.0.0.l1").mkdir()

            result = module.install_downloaded_update(version_dir)

        self.assertFalse(result.ok)
        self.assertEqual(result.exit_code, module.EXIT_USER_ERROR)
        self.assertIn(
            "newer installed version exists: v3.0.0.l1", result.errors[0]
        )

    def test_module_zip_bootstrap_creates_populated_release_version(self) -> None:
        """Installing a module bootstrap stages and extracts its ZIP release."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = Path(tmpdir) / "ModuleBootstrap"
            version_dir = package_root / "vbootstrap.l1"
            local_dir = version_dir / "pkg.local"
            local_dir.mkdir(parents=True)
            self.write_config(
                version_dir,
                """
                name = "ModuleBootstrap"
                version = "bootstrap"
                localVersion = 1

                [update]

                [update.check]
                mode = "module"

                [update.payload]
                mode = "zip"
                ignore_checksum = true
                """,
            )
            local_dir.joinpath("check_update.py").write_text(
                textwrap.dedent(
                    """
                    PKG_MODULE_API = 1

                    def check_update(context):
                        return {
                            "candidateId": "release:2.0.0",
                            "version": "2.0.0",
                            "url": "https://example.invalid/tool.zip",
                        }
                    """
                ).lstrip(),
                encoding="utf-8",
            )
            archive = self.zip_bytes({"tool.exe": "release payload"})

            # Keep HTTP and Windows junction boundaries controlled while
            # exercising module loading, staging, extraction, and metadata.
            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "is_current_user_admin", return_value=False
                ):
                    with mock.patch.object(
                        module,
                        "update_current_junction_if_needed",
                        return_value=True,
                    ):
                        with mock.patch.object(
                            runtime_module("updates").urllib.request,
                            "urlopen",
                            return_value=io.BytesIO(archive),
                        ):
                            result = module.install_package(version_dir)

            release_dir = package_root / "v2.0.0.l1"
            self.assertTrue(result.ok, msg=result.errors)
            self.assertTrue(result.changed)
            self.assertEqual(
                (release_dir / "App" / "tool.exe").read_text(encoding="utf-8"),
                "release payload",
            )
            release_config = tomllib.loads(
                (release_dir / "pkg.toml").read_text(encoding="utf-8")
            )
            self.assertEqual(release_config["version"], "2.0.0")
            self.assertEqual(release_config["localVersion"], 1)
            self.assertFalse((version_dir / "App").exists())

    def test_zip_payload_stages_a_direct_executable_release(self) -> None:
        """A ZIP-mode update installs an executable release without archive extraction."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = Path(tmpdir) / "ExecutableBootstrap"
            version_dir = package_root / "vbootstrap.l1"
            local_dir = version_dir / "pkg.local"
            local_dir.mkdir(parents=True)
            self.write_config(
                version_dir,
                """
                name = "ExecutableBootstrap"
                version = "bootstrap"
                localVersion = 1

                [update]

                [update.check]
                mode = "module"

                [update.payload]
                mode = "zip"
                ignore_checksum = true
                """,
            )
            local_dir.joinpath("check_update.py").write_text(
                textwrap.dedent(
                    """
                    PKG_MODULE_API = 1

                    def check_update(context):
                        return {
                            "candidateId": "release:2.0.0",
                            "version": "2.0.0",
                            "url": "https://example.invalid/tool.exe",
                        }
                    """
                ).lstrip(),
                encoding="utf-8",
            )
            executable = b"MZ executable payload"

            # Keep HTTP and Windows junction boundaries controlled while
            # exercising module loading, staging, and executable deployment.
            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "is_current_user_admin", return_value=False
                ):
                    with mock.patch.object(
                        module,
                        "update_current_junction_if_needed",
                        return_value=True,
                    ):
                        with mock.patch.object(
                            runtime_module("updates").urllib.request,
                            "urlopen",
                            return_value=io.BytesIO(executable),
                        ):
                            result = module.install_package(version_dir)

            release_dir = package_root / "v2.0.0.l1"
            self.assertTrue(result.ok, msg=result.errors)
            self.assertEqual(
                (release_dir / "App" / "tool.exe").read_bytes(), executable
            )

    def test_github_zip_bootstrap_extracts_and_renames_configured_paths(self) -> None:
        """ZIP mappings select archive contents and rename the staged executable."""
        module = load_gupkg_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = Path(tmpdir) / "GithubBootstrap"
            version_dir = package_root / "vbootstrap.l1"
            version_dir.mkdir(parents=True)
            archive = self.zip_bytes(
                {
                    "tool-2.0.0/tool.exe": "release payload",
                    "documentation/guide.txt": "guide",
                    "unrelated/skip.txt": "skip",
                }
            )
            checksum = hashlib.sha256(archive).hexdigest()
            self.write_config(
                version_dir,
                """
                name = "GithubBootstrap"
                version = "bootstrap"
                localVersion = 1

                [origin]
                url = "https://github.com/owner/tool"

                [update]

                [update.check]
                mode = "github"
                assetName = "tool_Windows_x86_64.zip"

                [update.payload]
                mode = "zip"

                [[update.payload.extract]]
                src = "tool-*/"
                dest = ""

                [[update.payload.extract]]
                src = "documentation"
                dest = "share"

                [[update.payload.rename]]
                src = "tool.exe"
                dest = "renamed-tool.exe"
                """,
            )
            release = json.dumps(
                {
                    "id": 42,
                    "tag_name": "v2.0.0",
                    "assets": [
                        {
                            "name": "tool_Windows_x86_64.zip",
                            "state": "uploaded",
                            "browser_download_url": (
                                "https://github.com/owner/tool/releases/"
                                "download/v2.0.0/tool_Windows_x86_64.zip"
                            ),
                            "digest": f"sha256:{checksum}",
                        }
                    ],
                }
            ).encode()

            # Keep HTTP and Windows junction boundaries controlled while
            # exercising built-in discovery, staging, verification, and extraction.
            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "is_current_user_admin", return_value=False
                ):
                    with mock.patch.object(
                        module,
                        "update_current_junction_if_needed",
                        return_value=True,
                    ):
                        with mock.patch.object(
                            runtime_module("updates").urllib.request,
                            "urlopen",
                            side_effect=[io.BytesIO(release), io.BytesIO(archive)],
                        ):
                            result = module.install_package(version_dir)

            release_dir = package_root / "v2.0.0.l1"
            self.assertTrue(result.ok, msg=result.errors)
            self.assertTrue(result.changed)
            self.assertEqual(
                (release_dir / "App" / "renamed-tool.exe").read_text(
                    encoding="utf-8"
                ),
                "release payload",
            )
            self.assertFalse((release_dir / "App" / "tool.exe").exists())
            self.assertEqual(
                (
                    release_dir / "App" / "share" / "documentation" / "guide.txt"
                ).read_text(encoding="utf-8"),
                "guide",
            )
            self.assertFalse((release_dir / "App" / "unrelated").exists())
            self.assertFalse((version_dir / "App").exists())

    def test_update_config_creates_documented_starter_file_when_missing(self) -> None:
        """Update config creates documented starter file when missing."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"

            code, output = self.run_main(
                module, ["config", "update", str(version_dir)]
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            gupkg_toml = version_dir / "pkg.toml"
            self.assertTrue(gupkg_toml.exists())
            self.assert_documented_starter_config(
                gupkg_toml.read_text(encoding="utf-8"),
                name="NoConfigApp",
                version="0.9.0",
                local_version=1,
            )

    def test_convert_legacy_action_writes_canonical_toml(self) -> None:
        """Config from-legacy writes canonical TOML through the main gupkg CLI."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "LegacyApp" / "v2.3.4.l5"
            version_dir.mkdir(parents=True)
            (version_dir / "opt_pkg.json").write_text(
                json.dumps(
                    {
                        "name": "LegacyApp",
                        "version": "2.3.4",
                        "local_version": 5,
                        "portable": False,
                    }
                ),
                encoding="utf-8",
            )

            code, output = self.run_main(
                module,
                ["config", "from-legacy", str(version_dir)],
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            parsed = tomllib.loads(
                (version_dir / "pkg.toml").read_text(encoding="utf-8")
            )
            self.assertEqual(parsed["name"], "LegacyApp")
            self.assertEqual(parsed["version"], "2.3.4")
            self.assertEqual(parsed["localVersion"], 5)
            self.assertFalse(parsed["only_portable"])

    def test_convert_legacy_dry_run_emits_only_parseable_toml(self) -> None:
        """Config from-legacy dry-run emits parseable TOML without writing output."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "DryLegacy" / "v1.0.0.l2"
            version_dir.mkdir(parents=True)
            (version_dir / "opt_pkg.json").write_text(
                json.dumps(
                    {
                        "name": "DryLegacy",
                        "version": "1.0.0",
                        "local_version": 2,
                    }
                ),
                encoding="utf-8",
            )

            code, output = self.run_main(
                module,
                [
                    "--dry-run",
                    "config",
                    "from-legacy",
                    str(version_dir),
                ],
            )

            self.assertEqual(code, module.EXIT_SUCCESS)
            parsed = tomllib.loads(output)
            self.assertEqual(parsed["name"], "DryLegacy")
            self.assertEqual(parsed["localVersion"], 2)
            self.assertFalse((version_dir / "pkg.toml").exists())

    def test_update_config_default_path_uses_caller_current_directory(self) -> None:
        """Update config default path uses caller current directory."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "DotApp")

            with pushd(version_dir):
                code, output = self.run_main(module, ["config", "update"])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertTrue((version_dir / "pkg.toml").exists())

    def test_update_config_uses_the_only_version_directory_when_current_is_missing(
        self,
    ) -> None:
        """Update config uses the only version directory when current is missing."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"

            code, output = self.run_main(
                module, ["config", "update", str(package_root)]
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            gupkg_toml = version_dir / "pkg.toml"
            self.assertTrue(gupkg_toml.exists())
            self.assert_documented_starter_config(
                gupkg_toml.read_text(encoding="utf-8"),
                name="NoConfigApp",
                version="0.9.0",
                local_version=1,
            )

    def test_update_config_rejects_an_ambiguous_package_root_without_current(
        self,
    ) -> None:
        """Update config rejects an ambiguous package root without current."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = Path(tmpdir) / "AmbiguousApp"
            (package_root / "v1.0.0.l1").mkdir(parents=True)
            (package_root / "v2.0.0.l1").mkdir()

            code, output = self.run_main(
                module, ["config", "update", str(package_root)]
            )

            self.assertEqual(code, module.EXIT_USER_ERROR, msg=output)
            self.assertIn("contains multiple version directories", output)

    def test_update_config_syncs_metadata_and_preserves_existing_content(self) -> None:
        """Update config syncs metadata and preserves existing content."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "MismatchApp")
            version_dir = package_root / "v2.0.0.l3"

            code, output = self.run_main(
                module, ["config", "update", str(version_dir)]
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            gupkg_toml = version_dir / "pkg.toml"
            updated = gupkg_toml.read_text(encoding="utf-8")
            backup = (version_dir / "pkg.toml.bak").read_text(encoding="utf-8")
            parsed = tomllib.loads(updated)

            self.assertEqual(parsed["name"], "MismatchApp")
            self.assertEqual(parsed["version"], "2.0.0")
            self.assertEqual(parsed["localVersion"], 3)
            self.assertIn("# Name is stale on purpose.", updated)
            self.assertIn('targetPath = "$App\\\\Mismatch.exe"', updated)
            self.assertIn('name = "MismatchApp-OLD"', backup)

    def test_update_config_syncs_metadata_without_validating_runtime_entries(
        self,
    ) -> None:
        """Update config syncs metadata without validating runtime entries."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "BrokenWriteApp", "v1.0.0.l2")
            self.write_config(
                version_dir,
                """
                # Keep this comment
                name = "BrokenWriteApp-OLD"
                version = "0.9.0"
                localVersion = 7
                only_portable = false

                [[shortcut]]
                name = "Broken Shortcut"
                x_note = "preserve me"
                """,
            )

            code, output = self.run_main(
                module, ["config", "update", str(version_dir)]
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn("# Keep this comment", updated)
            self.assertIn('name = "BrokenWriteApp"', updated)
            self.assertIn('version = "1.0.0"', updated)
            self.assertIn("localVersion = 2", updated)
            self.assertIn('x_note = "preserve me"', updated)
            self.assertNotIn("targetPath", updated)

    def test_update_config_preserves_hash_inside_quoted_metadata_string(self) -> None:
        """Update config preserves hash inside quoted metadata string."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "C#Tool")
            self.write_config(
                version_dir,
                """
                # Keep this comment
                name = "C#Tool-OLD"
                version = "0.9.0"
                localVersion = 9
                only_portable = false
                description = "preserve me"
                """,
            )

            code, output = self.run_main(
                module, ["config", "update", str(version_dir)]
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            parsed = tomllib.loads(updated)
            self.assertEqual(parsed["name"], "C#Tool")
            self.assertIn('name = "C#Tool"', updated)
            self.assertNotIn('"C#Tool"#Tool-OLD"', updated)

    def test_install_without_config_uses_defaults_without_writing_or_creating_bin(
        self,
    ) -> None:
        """Install without config uses defaults without writing or creating bin."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertIn("using defaults without creating a file", output)
            self.assertFalse((version_dir / "pkg.toml").exists())
            self.assertFalse((Path(env["USERPROFILE"]) / "bin").exists())

    def test_install_uses_the_only_version_directory_when_current_is_missing(
        self,
    ) -> None:
        """Install uses the only version directory when current is missing."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ) as junction_mock:
                    with mock.patch.object(
                        module,
                        "install_components",
                        return_value=mock.Mock(
                            ok=True, changed=False, warnings=[], errors=[]
                        ),
                    ) as components_mock:
                        code, output = self.run_main(module, ["install", str(package_root)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            junction_mock.assert_called_once()
            self.assertEqual(junction_mock.call_args.args[0].version_path, version_dir)
            components_mock.assert_called_once()

    def test_install_rejects_legacy_config_aliases_with_actionable_error(self) -> None:
        """Install rejects legacy config aliases with actionable error."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "AliasApp")
            self.write_config(
                version_dir,
                """
                name = "AliasApp"
                version = "1.0.0"
                localVersion = 1

                ENV = [{ Name = "ALIAS_HOME", Value = "$App" }]
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn(
                "Unsupported legacy key 'ENV' in config. Use 'environment' instead.",
                output,
            )

    def test_install_aborts_on_metadata_mismatch_before_mutations(self) -> None:
        """Install aborts on metadata mismatch before mutations."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "MismatchApp")
            version_dir = package_root / "v2.0.0.l3"

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed"
                ) as junction_mock:
                    with mock.patch.object(
                        module, "install_components"
                    ) as components_mock:
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            junction_mock.assert_not_called()
            components_mock.assert_not_called()
            self.assertIn("Configuration inconsistencies detected", output)
            self.assertIn(f"gupkg config update {version_dir}", output)
            self.assertIn(
                'name = "MismatchApp-OLD"',
                (version_dir / "pkg.toml").read_text(encoding="utf-8"),
            )
            self.assertFalse((version_dir / "pkg.toml.bak").exists())

    def test_install_accepts_package_name_that_differs_only_by_case(self) -> None:
        """Package-directory and configured names compare case-insensitively."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "CaseSensitiveApp")
            self.write_config(
                version_dir,
                """
                name = "casesensitiveapp"
                version = "1.0.0"
                localVersion = 1
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        module,
                        "install_components",
                        return_value=mock.Mock(
                            ok=True, changed=False, warnings=[], errors=[]
                        ),
                    ):
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)

    def test_update_config_uses_the_package_directory_name_case(self) -> None:
        """Config update writes the package directory's exact name spelling."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "CaseSensitiveApp")
            self.write_config(
                version_dir,
                """
                name = "casesensitiveapp"
                version = "1.0.0"
                localVersion = 1
                """,
            )

            code, output = self.run_main(
                module, ["config", "update", str(version_dir)]
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertIn(
                'name = "CaseSensitiveApp"',
                (version_dir / "pkg.toml").read_text(encoding="utf-8"),
            )

    def test_config_update_imports_and_archives_shortcuts_by_default(self) -> None:
        """Config update records _shortcuts entries and archives their source files."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ShortcutApp")
            shortcuts_dir = version_dir / "_shortcuts"
            shortcuts_dir.mkdir()
            source = shortcuts_dir / "Launch.lnk"
            source.write_text("", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "ShortcutApp"
                version = "1.0.0"
                localVersion = 1
                """,
            )

            payload = {
                "TargetPath": str(version_dir / "App" / "shortcut-app.exe"),
                "Arguments": "",
                "WorkingDirectory": "",
                "IconLocation": "",
                "Description": "Launch ShortcutApp",
            }
            with mock.patch(
                "gupkg.shortcuts_to_gupkg_toml.read_windows_shortcut",
                return_value=payload,
            ):
                code, output = self.run_main(
                    module, ["config", "update", str(version_dir)]
                )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            config_text = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn('name = "Launch"', config_text)
            self.assertFalse(source.exists())
            self.assertTrue(shortcuts_dir.joinpath("Launch.lnk.imported").exists())

    def test_config_update_can_leave_shortcut_sources_unimported(self) -> None:
        """An explicit false shortcut option leaves _shortcuts files untouched."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ShortcutApp")
            shortcuts_dir = version_dir / "_shortcuts"
            shortcuts_dir.mkdir()
            source = shortcuts_dir / "Launch.lnk"
            source.write_text("", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "ShortcutApp"
                version = "1.0.0"
                localVersion = 1
                """,
            )

            code, output = self.run_main(
                module,
                ["--import-shortcuts=false", "config", "update", str(version_dir)],
            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            config_text = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertNotIn("[[shortcut]]", config_text)
            self.assertTrue(source.exists())

    def test_auto_scope_uses_admin_status_and_portability_policy(self) -> None:
        """Automatic scope selects Machine only for permitted administrator installs."""
        cases = (
            ("admin-machine", True, False, "Machine"),
            ("admin-portable-user", True, True, "User"),
            ("nonadmin-user", False, False, "User"),
        )

        for case, is_admin, only_portable, expected_scope in cases:
            with self.subTest(case=case):
                module = load_gupkg_module()
                with tempfile.TemporaryDirectory() as tmpdir:
                    package_name = (
                        f"AutoScope-{case}-portable"
                        if only_portable
                        else f"AutoScope-{case}"
                    )
                    version_dir = self.make_version_dir(
                        tmpdir, package_name
                    )
                    self.write_config(
                        version_dir,
                        f"""
                        name = "{package_name}"
                        version = "1.0.0"
                        localVersion = 1
                        only_portable = {str(only_portable).lower()}
                        """,
                    )
                    env = self.user_env(tmpdir) | self.machine_env(tmpdir)

                    with mock.patch.dict(os.environ, env, clear=False):
                        with mock.patch.object(
                            module,
                            "is_current_user_admin",
                            return_value=is_admin,
                        ):
                            with mock.patch.object(
                                module,
                                "update_current_junction_if_needed",
                                return_value=True,
                            ):
                                code, output = self.run_main(
                                    module, ["install", str(version_dir)]
                                )

                self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
                self.assertIn(f"Selected scope: {expected_scope}", output)

    def test_shortcut_creation_failure_makes_install_fail(self) -> None:
        """Shortcut creation failure makes install fail."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ShortcutFailureApp")
            self.write_config(
                version_dir,
                r"""
                name = "ShortcutFailureApp"
                version = "1.0.0"
                localVersion = 1

                [[shortcut]]
                name = "Broken Shortcut"
                targetPath = "C:\\Tools\\missing.exe"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"),
                        "create_shortcut",
                        side_effect=RuntimeError("boom"),
                    ):
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertIn("Failed to create shortcut 'Broken Shortcut': boom", output)

    def test_unresolved_path_variable_makes_install_fail_before_registry_write(
        self,
    ) -> None:
        """Unresolved path variable makes install fail before registry write."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "BadPathApp")
            version_dir = package_root / "v1.0.0.l1"

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertIn("unresolved variable", output)

    def test_unresolved_shortcut_variable_makes_install_fail_before_shortcut_creation(
        self,
    ) -> None:
        """Unresolved shortcut variable makes install fail before shortcut creation."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ShortcutApp")
            self.write_config(
                version_dir,
                r"""
                name = "ShortcutApp"
                version = "1.0.0"
                localVersion = 1

                [[shortcut]]
                name = "Broken Shortcut"
                targetPath = "${MISSING_VAR}\\App.exe"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"), "create_shortcut"
                    ) as create_shortcut_mock:
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            create_shortcut_mock.assert_not_called()
            self.assertIn("unresolved variable", output)

    def test_bin_name_outside_default_root_is_allowed_but_warned(self) -> None:
        """Bin name outside default root is allowed but warned."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "WarnBinApp")
            self.write_config(
                version_dir,
                """
                name = "WarnBinApp"
                version = "1.0.0"
                localVersion = 1

                [[bin]]
                name = "../outside.cmd"
                content = "@echo off\\r\\n"
                """,
            )
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"),
                        "ensure_bin_in_path",
                        return_value=mock.Mock(
                            ok=True, changed=False, warnings=[], errors=[]
                        ),
                    ):
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertTrue((Path(env["USERPROFILE"]) / "outside.cmd").exists())
            self.assertIn(
                "WARNING: bin output resolves outside the default bin root", output
            )

    def test_shortcut_name_outside_default_root_is_allowed_but_warned(self) -> None:
        """Shortcut name outside default root is allowed but warned."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "WarnShortcutApp")
            self.write_config(
                version_dir,
                r"""
                name = "WarnShortcutApp"
                version = "1.0.0"
                localVersion = 1

                [[shortcut]]
                name = "../outside"
                targetPath = "C:\\Tools\\tool.exe"
                """,
            )
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"), "create_shortcut"
                    ) as create_shortcut_mock:
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            shortcut_path = create_shortcut_mock.call_args.args[0]
            default_root = (
                Path(env["APPDATA"]) / "Microsoft" / "Windows" / "Start Menu" / "opt"
            )
            self.assertFalse(
                shortcut_path.resolve(strict=False).is_relative_to(
                    default_root.resolve(strict=False)
                )
            )
            self.assertIn(
                "WARNING: shortcut output resolves outside the default shortcut root",
                output,
            )

    def test_bin_wrapper_content_keeps_shell_variables_and_expands_braced_env(
        self,
    ) -> None:
        """Bin wrapper content keeps shell variables and expands braced env."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "PwshScriptApp")
            self.write_config(
                version_dir,
                """
                name = "PwshScriptApp"
                version = "1.0.0"
                localVersion = 1

                [[bin]]
                name = "tool.ps1"
                content = '''
                $ErrorActionPreference = 'Stop'
                ${SystemRoot}
                $app = Join-Path $PSScriptRoot 'Tool.exe'
                & $app @args
                '''
                """,
            )
            env = self.user_env(tmpdir)
            env["SystemRoot"] = r"C:\Windows"

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"),
                        "ensure_bin_in_path",
                        return_value=mock.Mock(
                            ok=True, changed=False, warnings=[], errors=[]
                        ),
                    ):
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            written = (Path(env["USERPROFILE"]) / "bin" / "tool.ps1").read_text(
                encoding="utf-8"
            )
            self.assertIn("$ErrorActionPreference = 'Stop'", written)
            self.assertIn(r"C:\Windows", written)
            self.assertIn("$app = Join-Path $PSScriptRoot 'Tool.exe'", written)
            self.assertIn("& $app @args", written)

    def test_bin_command_generates_a_batch_wrapper_with_declared_arguments(
        self,
    ) -> None:
        """Command-form wrappers add fixed arguments and forward caller arguments."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "CommandBinApp")
            self.write_config(
                version_dir,
                """
                name = "CommandBinApp"
                version = "1.0.0"
                localVersion = 1

                [[bin]]
                name = "tool.cmd"
                command = '\"$App\\Tool.exe\"'
                extra_args = "--fixed value"
                forward_args = true
                """,
            )
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"),
                        "ensure_bin_in_path",
                        return_value=mock.Mock(
                            ok=True, changed=False, warnings=[], errors=[]
                        ),
                    ):
                        code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            written = (Path(env["USERPROFILE"]) / "bin" / "tool.cmd").read_text(
                encoding="ascii"
            )
            self.assertEqual(
                written,
                f'@echo off\ncall "{version_dir.parent / "current" / "App" / "Tool.exe"}" --fixed value %*\n',
            )

    def test_bin_content_rejects_command_form_options(self) -> None:
        """Custom wrapper content cannot be combined with generated-wrapper options."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ContentBinApp")
            self.write_config(
                version_dir,
                """
                name = "ContentBinApp"
                version = "1.0.0"
                localVersion = 1

                [[bin]]
                name = "tool.cmd"
                content = "@echo off"
                forward_args = false
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn(
                "cannot be combined with command-form wrapper options", output
            )

    def test_install_updates_existing_wrapper_file(self) -> None:
        """Install updates existing wrapper file."""
        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "WrapperRepairApp")
            env = self.user_env(tmpdir)

            def write_wrapper_config(message: str) -> None:
                self.write_config(
                    version_dir,
                    f"""
                    name = "WrapperRepairApp"
                    version = "1.0.0"
                    localVersion = 1

                    [[bin]]
                    name = "tool.cmd"
                    content = "@echo off\\r\\necho {message}\\r\\n"
                    """,
                )

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        runtime_module("components"),
                        "ensure_bin_in_path",
                        return_value=mock.Mock(
                            ok=True, changed=False, warnings=[], errors=[]
                        ),
                    ):
                        write_wrapper_config("one")
                        first_code, first_output = self.run_main(
                            module, ["install", str(version_dir)]
                        )
                        write_wrapper_config("two")
                        second_code, second_output = self.run_main(
                            module, ["install", str(version_dir)]
                        )

            self.assertEqual(first_code, module.EXIT_SUCCESS, msg=first_output)
            self.assertEqual(second_code, module.EXIT_SUCCESS, msg=second_output)
            written = (Path(env["USERPROFILE"]) / "bin" / "tool.cmd").read_text(
                encoding="ascii"
            )
            self.assertIn("echo two", written)
            self.assertNotIn("echo one", written)

    def test_install_rejects_top_level_download_url(self) -> None:
        """Install rejects the removed top-level downloadURL schema."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "OldDownloadApp")
            self.write_config(
                version_dir,
                """
                name = "OldDownloadApp"
                version = "1.0.0"
                localVersion = 1
                downloadURL = "https://example.invalid/app.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("Unsupported legacy key 'downloadURL'", output)

    def test_install_populates_missing_app_from_zip_origin_before_components(
        self,
    ) -> None:
        """Install downloads a zip origin into a missing App before installing components."""

        module = load_gupkg_module()
        archive = self.zip_bytes({"tool/tool.exe": "payload"})
        checksum = hashlib.sha256(archive).hexdigest()

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ZipOriginApp")
            self.write_config(
                version_dir,
                f"""
                name = "ZipOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                checksum = "sha256:{checksum}"
                extractSubdir = "tool"
                """,
            )

            def assert_app_ready(*_args, **_kwargs):
                self.assertEqual(
                    (version_dir / "App" / "tool.exe").read_text(encoding="utf-8"),
                    "payload",
                )
                return mock.Mock(ok=True, changed=False, warnings=[], errors=[])

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        urllib.request, "urlopen", return_value=io.BytesIO(archive)
                    ) as urlopen_mock:
                        with mock.patch.object(
                            module, "install_components", side_effect=assert_app_ready
                        ):
                            code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_called_once_with("https://example.invalid/tool.zip")
            self.assertIn("Verifying sha256 checksum", output)

    def test_install_skips_zip_origin_when_app_is_already_populated(self) -> None:
        """Install does not download origin when App already contains entries."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "SkipOriginApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "existing.txt").write_text("keep", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "SkipOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(urllib.request, "urlopen") as urlopen_mock:
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=mock.Mock(
                                ok=True, changed=False, warnings=[], errors=[]
                            ),
                        ):
                            code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_not_called()
            self.assertEqual(
                (version_dir / "App" / "existing.txt").read_text(encoding="utf-8"),
                "keep",
            )
            self.assertIn(
                "App is already populated; skipping origin population", output
            )

    def test_install_selects_versioned_origin_matching_package_version(self) -> None:
        """Install uses the versioned origin entry matching the package version."""

        module = load_gupkg_module()
        archive = self.zip_bytes({"selected.exe": "selected"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "SelectedOriginApp")
            self.write_config(
                version_dir,
                """
                name = "SelectedOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "0.9"
                url = "https://example.invalid/old.zip"

                [[origin.versions]]
                version = "1.0.0"
                url = "https://example.invalid/current.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        urllib.request, "urlopen", return_value=io.BytesIO(archive)
                    ) as urlopen_mock:
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=mock.Mock(
                                ok=True, changed=False, warnings=[], errors=[]
                            ),
                        ):
                            code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_called_once_with("https://example.invalid/current.zip")
            self.assertTrue((version_dir / "App" / "selected.exe").exists())

    def test_refresh_app_replaces_existing_app_from_zip_origin(self) -> None:
        """--refresh-app replaces existing App contents from a zip origin."""

        module = load_gupkg_module()
        archive = self.zip_bytes({"new.exe": "new"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "RefreshOriginApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "old.exe").write_text("old", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "RefreshOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        urllib.request, "urlopen", return_value=io.BytesIO(archive)
                    ):
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=mock.Mock(
                                ok=True, changed=False, warnings=[], errors=[]
                            ),
                        ):
                            code, output = self.run_main(
                                module, ["--refresh-app", "install", str(version_dir)]
                            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertEqual(
                (version_dir / "App" / "new.exe").read_text(encoding="utf-8"), "new"
            )
            self.assertFalse((version_dir / "App" / "old.exe").exists())

    def test_install_fails_when_selected_origin_version_has_no_source(self) -> None:
        """Install fails only when an incomplete versioned origin is used."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "IncompleteCurrentOriginApp")
            self.write_config(
                version_dir,
                """
                name = "IncompleteCurrentOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "1.0.0"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertIn("does not declare url or script", output)

    def test_checksum_mismatch_aborts_without_app_mutation(self) -> None:
        """Checksum mismatch fails before replacing an existing App directory."""

        module = load_gupkg_module()
        archive = self.zip_bytes({"new.exe": "new"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ChecksumOriginApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "old.exe").write_text("old", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "ChecksumOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        urllib.request, "urlopen", return_value=io.BytesIO(archive)
                    ):
                        code, output = self.run_main(
                            module, ["--refresh-app", "install", str(version_dir)]
                        )

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertEqual(
                (version_dir / "App" / "old.exe").read_text(encoding="utf-8"), "old"
            )
            self.assertIn("[origin].checksum did not match downloaded file", output)

    def test_unsafe_zip_path_aborts_without_app_mutation(self) -> None:
        """Unsafe archive paths are rejected before App is replaced."""

        module = load_gupkg_module()
        archive = self.zip_bytes({"../escape.exe": "bad"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "UnsafeZipApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "old.exe").write_text("old", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "UnsafeZipApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        urllib.request, "urlopen", return_value=io.BytesIO(archive)
                    ):
                        code, output = self.run_main(
                            module, ["--refresh-app", "install", str(version_dir)]
                        )

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertEqual(
                (version_dir / "App" / "old.exe").read_text(encoding="utf-8"), "old"
            )
            self.assertIn("unsafe path", output)

    def test_no_checksum_allows_install_with_warning(self) -> None:
        """--no-checksum skips configured checksum verification and warns."""

        module = load_gupkg_module()
        archive = self.zip_bytes({"tool.exe": "payload"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "NoChecksumOriginApp")
            self.write_config(
                version_dir,
                """
                name = "NoChecksumOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        urllib.request, "urlopen", return_value=io.BytesIO(archive)
                    ):
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=mock.Mock(
                                ok=True, changed=False, warnings=[], errors=[]
                            ),
                        ):
                            code, output = self.run_main(
                                module, ["--no-checksum", "install", str(version_dir)]
                            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertTrue((version_dir / "App" / "tool.exe").exists())
            self.assertIn("WARNING: Checksum verification skipped", output)

    def test_script_origin_receives_payload_and_working_directory(self) -> None:
        """Script origin receives enriched JSON on stdin and runs from the script directory."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ScriptOriginApp")
            script_dir = version_dir / "scripts"
            script_dir.mkdir()
            script_path = script_dir / "populate.cmd"
            script_path.write_text("@echo off\r\n", encoding="ascii")
            self.write_config(
                version_dir,
                """
                name = "ScriptOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                script = "scripts/populate.cmd"
                """,
            )

            def run_script(*_args, **kwargs):
                payload = json.loads(kwargs["input"])
                self.assertEqual(payload["identity"]["name"], "ScriptOriginApp")
                self.assertNotIn("version", payload["config"]["origin"])
                self.assertEqual(
                    Path(payload["PkgVars"]["App"]).resolve(),
                    (version_dir / "App").resolve(),
                )
                self.assertEqual(Path(kwargs["cwd"]).resolve(), script_dir.resolve())
                app_dir = version_dir / "App"
                app_dir.mkdir()
                (app_dir / "created.txt").write_text("ok", encoding="utf-8")
                return subprocess.CompletedProcess(
                    args=[], returncode=0, stdout="", stderr=""
                )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=True
                ):
                    with mock.patch.object(
                        subprocess, "run", side_effect=run_script
                    ) as run_mock:
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=mock.Mock(
                                ok=True, changed=False, warnings=[], errors=[]
                            ),
                        ):
                            code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            run_mock.assert_called_once()
            self.assertTrue((version_dir / "App" / "created.txt").exists())

    def test_health_check_accepts_valid_origin_history(self) -> None:
        """Config check validates origin history without downloading or installing."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "HealthyOriginApp")
            script_dir = version_dir / "scripts"
            script_dir.mkdir()
            (script_dir / "populate.cmd").write_text("@echo off\r\n", encoding="ascii")
            self.write_config(
                version_dir,
                """
                name = "HealthyOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "0.9"
                url = "https://example.invalid/old.zip"

                [[origin.versions]]
                version = "1.0.0"
                script = "scripts/populate.cmd"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(urllib.request, "urlopen") as urlopen_mock:
                    code, output = self.run_main(
                        module, ["config", "check", str(version_dir)]
                    )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_not_called()
            self.assertIn("Health check passed.", output)

    def test_health_check_accepts_origin_history_without_sources(self) -> None:
        """Config check accepts version-only origin history entries."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "VersionOnlyOriginApp")
            self.write_config(
                version_dir,
                """
                name = "VersionOnlyOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "0.9"

                [[origin.versions]]
                version = "1.0.0"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(
                    module, ["config", "check", str(version_dir)]
                )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertIn("Health check passed.", output)

    def test_health_check_rejects_duplicate_origin_history_versions(self) -> None:
        """Config check reports duplicate versioned origin entries."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "DuplicateOriginApp")
            self.write_config(
                version_dir,
                """
                name = "DuplicateOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "1.0"
                url = "https://example.invalid/one.zip"

                [[origin.versions]]
                version = "1.0"
                url = "https://example.invalid/two.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(
                    module, ["config", "check", str(version_dir)]
                )

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("duplicate version: 1.0", output)

    def test_health_check_rejects_missing_package_version_origin_history(self) -> None:
        """Config check reports origin history that lacks the package version."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "MissingSelectedOriginApp")
            self.write_config(
                version_dir,
                """
                name = "MissingSelectedOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "2.0"
                url = "https://example.invalid/one.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(
                    module, ["config", "check", str(version_dir)]
                )

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn(
                "[[origin.versions]] must contain an entry matching top-level version",
                output,
            )

    def test_health_check_rejects_top_level_origin_version(self) -> None:
        """Config check rejects removed top-level [origin].version syntax."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "OldSelectorOriginApp")
            self.write_config(
                version_dir,
                """
                name = "OldSelectorOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                version = "1.0.0"

                [[origin.versions]]
                version = "1.0.0"
                url = "https://example.invalid/one.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(
                    module, ["config", "check", str(version_dir)]
                )

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("Unknown key 'version' in origin", output)

    def test_health_check_rejects_bad_origin_script_reference(self) -> None:
        """Config check reports package-local script reference problems."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "BadScriptOriginApp")
            self.write_config(
                version_dir,
                """
                name = "BadScriptOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                script = "scripts/missing.cmd"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(
                    module, ["config", "check", str(version_dir)]
                )

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("[origin].script was not found", output)

    def test_newer_current_skip_also_skips_origin_population(self) -> None:
        """A preserved newer current skips origin population and component install."""

        module = load_gupkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "NewerCurrentApp")
            self.write_config(
                version_dir,
                """
                name = "NewerCurrentApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(
                    module, "update_current_junction_if_needed", return_value=False
                ):
                    with mock.patch.object(urllib.request, "urlopen") as urlopen_mock:
                        with mock.patch.object(
                            module, "install_components"
                        ) as install_components_mock:
                            code, output = self.run_main(module, ["install", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_not_called()
            install_components_mock.assert_not_called()


if __name__ == "__main__":
    unittest.main()
