from __future__ import annotations

import contextlib
import importlib.util
import io
import os
import shutil
import sys
import tempfile
import tomllib
from pathlib import Path
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
PKG_PY = ROOT / "pkg.py"
FIXTURES = ROOT / "tests" / "fixtures"


def load_pkg_module():
    spec = importlib.util.spec_from_file_location("pkg_under_test", PKG_PY)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(spec.name, None)
    return module


def resolve_identity(module, package_path: Path):
    identity, installing_from_current = module.resolve_input_path(Path(package_path))
    return identity, installing_from_current


def load_runtime_config(module, package_path: Path, *, use_defaults: bool = False):
    identity, _ = resolve_identity(module, package_path)
    runtime_config, raw_config, warnings = module.read_runtime_config(identity, use_defaults=use_defaults)
    return identity, runtime_config, raw_config, warnings


class PkgPureImportTests(unittest.TestCase):
    def assert_documented_starter_config(
        self,
        text: str,
        *,
        name: str,
        version: str,
        local_version: int,
        only_portable: bool = False,
    ) -> None:
        nonblank_lines = [line.strip() for line in text.splitlines() if line.strip()]
        self.assertTrue(nonblank_lines, msg="Starter config should not be empty.")
        header = nonblank_lines[0]
        self.assertTrue(header.startswith("#"), msg="Starter config should begin with a comment header.")
        self.assertIn("pkg", header.lower(), msg="Starter config header should identify pkg as the generator.")
        self.assertTrue(
            any(token in header.lower() for token in ("generated", "auto-generated", "autogenerated")),
            msg="Starter config header should indicate that the file was generated.",
        )
        self.assertIn(f'name = "{name}"', text)
        self.assertIn(f'version = "{version}"', text)
        self.assertIn(f"localVersion = {local_version}", text)
        self.assertIn(f"only_portable = {str(only_portable).lower()}", text)
        for example_block in ("shortcut", "environment", "path", "bin"):
            self.assertIn(f"# [[{example_block}]]", text)

    def test_import_succeeds(self) -> None:
        module = load_pkg_module()
        self.assertEqual(module.__version__, "0.12.0")

    def test_version_helpers_are_callable(self) -> None:
        module = load_pkg_module()
        self.assertTrue(module.is_version_directory_name("v1.2.3.l4"))
        self.assertEqual(module.compare_package_versions("v2.0.0.l1", "v1.9.9.l9"), 1)

    def test_install_package_accepts_machine_scope_argument(self) -> None:
        module = load_pkg_module()
        with contextlib.redirect_stdout(io.StringIO()):
            result = module.install_package(ROOT / "does-not-exist", scope=module.Scope.MACHINE)
        self.assertFalse(result.ok)
        self.assertEqual(result.exit_code, module.EXIT_USER_ERROR)

    def test_invalid_install_path_returns_nonzero(self) -> None:
        module = load_pkg_module()
        with contextlib.redirect_stdout(io.StringIO()):
            result = module.install_package(ROOT / "does-not-exist")
        self.assertFalse(result.ok)
        self.assertEqual(result.exit_code, module.EXIT_USER_ERROR)

    def test_invalid_config_returns_nonzero(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "BrokenApp" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            (version_dir / "pkg.toml").write_text(
                """name = "BrokenApp"
version = "1.0.0"
localVersion = 1

[[shortcut]]
name = "Broken"
""",
                encoding="utf-8",
            )
            with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                with contextlib.redirect_stdout(io.StringIO()):
                    result = module.install_package(version_dir)
            self.assertFalse(result.ok)
            self.assertEqual(result.exit_code, module.EXIT_USER_ERROR)

    def test_shortcut_creation_failure_returns_nonzero(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "GoodApp"
            dst = Path(tmpdir) / "GoodApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v1.2.3.l1"
            with mock.patch.object(module, "update_current_junction_if_needed", side_effect=lambda identity, force=False: True):
                with mock.patch.object(
                    module,
                    "install_shortcuts",
                    side_effect=lambda shortcuts, identity, scope_paths: module.StepResult(
                        ok=False,
                        errors=["Failed to create shortcut: Good App"],
                    ),
                ):
                    with mock.patch.object(
                        module,
                        "install_environment_variables",
                        side_effect=lambda environment_entries, identity, scope: module.StepResult(ok=True, changed=False),
                    ):
                        with mock.patch.object(
                            module,
                            "ensure_bin_in_path",
                            side_effect=lambda scope_paths, identity, scope: module.StepResult(ok=True, changed=False),
                        ):
                            with mock.patch.object(
                                module,
                                "add_to_path",
                                side_effect=lambda new_entries, identity, scope: module.StepResult(ok=True, changed=False),
                            ):
                                with mock.patch.object(
                                    module,
                                    "install_wrappers",
                                    side_effect=lambda wrapper_entries, identity, scope_paths: module.StepResult(ok=True, changed=False),
                                ):
                                    with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                                        with contextlib.redirect_stdout(io.StringIO()):
                                            result = module.install_package(version_dir)

            self.assertFalse(result.ok)
            self.assertEqual(result.exit_code, module.EXIT_MUTATION_ERROR)

    def test_missing_config_uses_defaults_without_writing(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "NoConfigApp"
            dst = Path(tmpdir) / "NoConfigApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v0.9.0.l1"
            identity, runtime, raw_config, warnings = load_runtime_config(module, version_dir)
            self.assertEqual(raw_config, {})
            self.assertTrue(warnings)
            self.assertEqual(identity.name, "NoConfigApp")
            self.assertEqual(runtime["shortcut"], [])
            self.assertEqual(runtime["environment"], [])
            self.assertEqual(runtime["path"], [])
            self.assertEqual(runtime["bin"], [])
            self.assertFalse((version_dir / "pkg.toml").exists())

    def test_metadata_consistency_detects_raw_file_mismatches(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "MismatchApp"
            dst = Path(tmpdir) / "MismatchApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v2.0.0.l3"
            identity, _runtime, config_data, warnings = load_runtime_config(module, version_dir)

            self.assertEqual(warnings, [])
            self.assertEqual(config_data["name"], "MismatchApp-OLD")
            self.assertEqual(config_data["version"], "1.9.9")
            self.assertEqual(config_data["localVersion"], 7)
            self.assertEqual(
                module.check_metadata_consistency(identity, config_data),
                [
                    "Name mismatch: directory='MismatchApp', config='MismatchApp-OLD'",
                    "Version mismatch: directory='2.0.0', config='1.9.9'",
                    "LocalVersion mismatch: directory='3', config='7'",
                ],
            )

    def test_matching_raw_config_has_no_metadata_mismatch(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "GoodApp"
            dst = Path(tmpdir) / "GoodApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v1.2.3.l1"
            identity, _runtime, config_data, warnings = load_runtime_config(module, version_dir)

            self.assertEqual(warnings, [])
            self.assertEqual(config_data["name"], "GoodApp")
            self.assertEqual(module.check_metadata_consistency(identity, config_data), [])

    def test_missing_config_with_defaults_does_not_trigger_metadata_mismatch(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "NoConfigApp"
            dst = Path(tmpdir) / "NoConfigApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v0.9.0.l1"
            identity, runtime, config_data, warnings = load_runtime_config(module, version_dir, use_defaults=True)

            self.assertTrue(warnings)
            self.assertEqual(config_data, {})
            self.assertEqual(module.check_metadata_consistency(identity, config_data), [])
            self.assertEqual(runtime["shortcut"], [])
            self.assertFalse((version_dir / "pkg.toml").exists())

    def test_install_aborts_on_metadata_mismatch_before_mutations(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "MismatchApp"
            dst = Path(tmpdir) / "MismatchApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v2.0.0.l3"
            calls = []

            def fake_update_current(identity, force=False):
                calls.append("junction")
                return True

            def fake_install_components(identity, scope, scope_paths, runtime_config):
                calls.append("components")
                return module.StepResult(ok=True, changed=False)

            with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", side_effect=fake_update_current):
                    with mock.patch.object(module, "install_components", side_effect=fake_install_components):
                        with contextlib.redirect_stdout(io.StringIO()) as output:
                            result = module.install_package(version_dir)

            self.assertFalse(result.ok)
            self.assertEqual(result.exit_code, module.EXIT_USER_ERROR)
            self.assertEqual(calls, [])
            self.assertIn("Configuration inconsistencies detected", output.getvalue())
            pkg_toml = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn('name = "MismatchApp-OLD"', pkg_toml)
            self.assertFalse((version_dir / "pkg.toml.bak").exists())

    def test_install_with_fix_config_repairs_metadata_then_continues(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "MismatchApp"
            dst = Path(tmpdir) / "MismatchApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v2.0.0.l3"
            calls = []

            def fake_update_current(identity, force=False):
                calls.append("junction")
                return True

            def fake_install_components(identity, scope, scope_paths, runtime_config):
                calls.append("components")
                return module.StepResult(ok=True, changed=False)

            with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", side_effect=fake_update_current):
                    with mock.patch.object(module, "install_components", side_effect=fake_install_components):
                        with contextlib.redirect_stdout(io.StringIO()) as output:
                            result = module.install_package(version_dir, fix_config=True)

            self.assertTrue(result.ok)
            self.assertEqual(result.exit_code, module.EXIT_SUCCESS)
            self.assertEqual(calls, ["junction", "components"])
            self.assertIn("Configuration updated successfully.", output.getvalue())
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            backup = (version_dir / "pkg.toml.bak").read_text(encoding="utf-8")
            self.assertIn('name = "MismatchApp"', updated)
            self.assertIn('version = "2.0.0"', updated)
            self.assertIn('localVersion = 3', updated)
            self.assertIn('name = "MismatchApp-OLD"', backup)

    def test_update_config_preserves_comments_unknown_keys_and_creates_backup(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "MismatchApp"
            dst = Path(tmpdir) / "MismatchApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v2.0.0.l3"
            with contextlib.redirect_stdout(io.StringIO()):
                result = module.update_package_config(version_dir, scope=module.Scope.MACHINE)
            self.assertTrue(result.ok)
            self.assertTrue(result.changed)

            pkg_toml = version_dir / "pkg.toml"
            updated = pkg_toml.read_text(encoding="utf-8")
            backup = (version_dir / "pkg.toml.bak").read_text(encoding="utf-8")

            self.assertIn('# Name is stale on purpose.', updated)
            self.assertIn('name = "MismatchApp"', updated)
            self.assertIn('version = "2.0.0"', updated)
            self.assertIn('localVersion = 3', updated)
            self.assertIn('only_portable = false', updated)
            self.assertIn('name = "MismatchApp-OLD"', backup)

    def test_resolve_input_path_classifies_version_dir_without_resolving_first(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "GoodApp" / "v1.2.3.l1"
            version_dir.mkdir(parents=True)
            identity, installing_from_current = module.resolve_input_path(version_dir)
            self.assertEqual(identity.version_path, version_dir)
            self.assertEqual(identity.package_root, version_dir.parent)
            self.assertFalse(installing_from_current)
            self.assertFalse(identity.is_current)

    def test_resolve_input_path_treats_dot_inside_version_dir_as_version_dir(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "GoodApp" / "v1.2.3.l1"
            version_dir.mkdir(parents=True)
            cwd = Path.cwd()
            try:
                os.chdir(version_dir)
                identity, installing_from_current = module.resolve_input_path(Path("."))
            finally:
                os.chdir(cwd)
            self.assertEqual(identity.package_root, version_dir.parent)
            self.assertEqual(identity.version_path, version_dir)
            self.assertFalse(installing_from_current)

    def test_install_banner_includes_operation_name(self) -> None:
        module = load_pkg_module()
        with contextlib.redirect_stdout(io.StringIO()) as output:
            result = module.install_package(ROOT / "does-not-exist")
        self.assertFalse(result.ok)
        self.assertIn("Operation: Install", output.getvalue())

    def test_update_config_banner_includes_operation_name(self) -> None:
        module = load_pkg_module()
        with contextlib.redirect_stdout(io.StringIO()) as output:
            result = module.update_package_config(ROOT / "does-not-exist")
        self.assertFalse(result.ok)
        self.assertIn("Operation: UpdateConfig", output.getvalue())

    def test_legacy_aliases_and_main_wrapper_are_rejected(self) -> None:
        module = load_pkg_module()
        identity = module.PackageIdentity(
            name="AliasApp",
            version="1.0.0",
            local_version=2,
            version_string="v1.0.0.l2",
            package_root=Path("C:/pkg/AliasApp"),
            version_path=Path("C:/pkg/AliasApp/v1.0.0.l2"),
            is_current=False,
            only_portable_by_name=False,
        )
        with self.assertRaises(module.ConfigValidationError) as alias_error:
            module.normalize_runtime_config({"ENV": [{"Name": "HOME", "Value": "$App"}]}, identity)
        self.assertIn("Unsupported legacy key 'ENV' in config. Use 'environment' instead.", str(alias_error.exception))

        with self.assertRaises(module.ConfigValidationError) as main_error:
            module.normalize_runtime_config({"main": [{"portable": True}]}, identity)
        self.assertIn(
            "Unsupported legacy key 'main' in config. Use canonical top-level metadata keys instead of [[main]].",
            str(main_error.exception),
        )

    def test_update_config_creates_starter_file_when_missing(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "NoConfigApp"
            dst = Path(tmpdir) / "NoConfigApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v0.9.0.l1"
            with contextlib.redirect_stdout(io.StringIO()):
                result = module.update_package_config(version_dir)
            self.assertTrue(result.ok)
            self.assertTrue(result.changed)
            pkg_toml = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assert_documented_starter_config(
                pkg_toml,
                name="NoConfigApp",
                version="0.9.0",
                local_version=1,
            )

            _identity, runtime, raw_config, warnings = load_runtime_config(module, version_dir)
            self.assertFalse(warnings)
            self.assertEqual(raw_config["name"], "NoConfigApp")
            self.assertEqual(raw_config["version"], "0.9.0")
            self.assertEqual(raw_config["localVersion"], 1)
            self.assertEqual(raw_config["only_portable"], False)
            self.assertEqual(runtime["shortcut"], [])
            self.assertEqual(runtime["environment"], [])
            self.assertEqual(runtime["path"], [])
            self.assertEqual(runtime["bin"], [])

    def test_update_config_syncs_existing_canonical_metadata_only_file_in_place(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "RegressionApp" / "v3.4.5.l6"
            version_dir.mkdir(parents=True)
            original = """name = "RegressionApp-OLD"
version = "0.0.1"
localVersion = 99
only_portable = false
"""
            (version_dir / "pkg.toml").write_text(original, encoding="utf-8")

            with contextlib.redirect_stdout(io.StringIO()):
                result = module.update_package_config(version_dir)

            self.assertTrue(result.ok)
            self.assertTrue(result.changed)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            backup = (version_dir / "pkg.toml.bak").read_text(encoding="utf-8")

            self.assertEqual(backup, original)
            self.assertIn('name = "RegressionApp"', updated)
            self.assertIn('version = "3.4.5"', updated)
            self.assertIn('localVersion = 6', updated)
            self.assertIn('only_portable = false', updated)
            self.assertNotIn('[[shortcut]]', updated)

    def test_update_config_syncs_metadata_without_validating_runtime_entries(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "BrokenWriteApp" / "v1.0.0.l2"
            version_dir.mkdir(parents=True)
            (version_dir / "pkg.toml").write_text(
                """# Keep this comment
name = "BrokenWriteApp-OLD"
version = "0.9.0"
localVersion = 7
only_portable = false

[[shortcut]]
name = "Broken Shortcut"
x_note = "preserve me"
""",
                encoding="utf-8",
            )
            with contextlib.redirect_stdout(io.StringIO()):
                result = module.update_package_config(version_dir)
            self.assertTrue(result.ok)
            self.assertTrue(result.changed)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn('# Keep this comment', updated)
            self.assertIn('name = "BrokenWriteApp"', updated)
            self.assertIn('version = "1.0.0"', updated)
            self.assertIn('localVersion = 2', updated)
            self.assertIn('x_note = "preserve me"', updated)
            self.assertNotIn('targetPath', updated)

    def test_update_config_preserves_hash_inside_quoted_metadata_string(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "C#Tool" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            (version_dir / "pkg.toml").write_text(
                """# Keep this comment
name = "C#Tool-OLD"
version = "0.9.0"
localVersion = 9
only_portable = false
description = "preserve me"
""",
                encoding="utf-8",
            )

            with contextlib.redirect_stdout(io.StringIO()):
                result = module.update_package_config(version_dir)

            self.assertTrue(result.ok)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            parsed = tomllib.loads(updated)
            self.assertEqual(parsed["name"], "C#Tool")
            self.assertIn('name = "C#Tool"', updated)
            self.assertNotIn('"C#Tool"#Tool-OLD"', updated)

    def test_install_with_fix_config_repairs_portable_flag_before_machine_scope_gate(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "MachineRepairApp" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            (version_dir / "pkg.toml").write_text(
                """name = "MachineRepairApp"
version = "1.0.0"
localVersion = 1
only_portable = true
""",
                encoding="utf-8",
            )

            stdout = io.StringIO()
            with mock.patch.dict(
                os.environ,
                {
                    "PROGRAMDATA": str(Path(tmpdir) / "ProgramData"),
                    "SYSTEMDRIVE": str(Path(tmpdir) / "Drive"),
                },
                clear=False,
            ):
                with mock.patch.object(module, "is_current_user_admin", return_value=True):
                    with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                        with mock.patch.object(module, "install_components", return_value=module.StepResult(ok=True, changed=False)):
                            with contextlib.redirect_stdout(stdout):
                                result = module.install_package(
                                    version_dir,
                                    scope=module.Scope.MACHINE,
                                    fix_config=True,
                                )

            self.assertTrue(result.ok)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn("only_portable = false", updated)
            output = stdout.getvalue()
            self.assertIn("Configuration updated successfully.", output)
            self.assertNotIn("only_portable packages cannot be installed system-wide", output)

    def test_bin_wrapper_name_outside_default_root_is_allowed_but_warned(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "WarnBinApp" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            identity, _ = resolve_identity(module, version_dir)
            with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                scope_paths = module.compute_scope_paths(module.Scope.USER)
                stdout = io.StringIO()
                with contextlib.redirect_stdout(stdout):
                    result = module.install_wrappers(
                        [{"name": "../outside.cmd", "content": "@echo off\r\n"}],
                        identity,
                        scope_paths,
                    )

            self.assertTrue(result.ok)
            self.assertTrue((Path(tmpdir) / "outside.cmd").exists())
            self.assertIn("WARNING: bin output resolves outside the default bin root", stdout.getvalue())

    def test_shortcut_name_outside_default_root_is_allowed_but_warned(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "WarnShortcutApp" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            identity, _ = resolve_identity(module, version_dir)
            with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                scope_paths = module.compute_scope_paths(module.Scope.USER)
                stdout = io.StringIO()
                with contextlib.redirect_stdout(stdout):
                    with mock.patch.object(module, "create_shortcut") as create_shortcut_mock:
                        result = module.install_shortcuts(
                            [{"name": "../outside", "targetPath": r"C:\Tools\tool.exe"}],
                            identity,
                            scope_paths,
                        )

            self.assertTrue(result.ok, msg=result.errors)
            shortcut_path = create_shortcut_mock.call_args.args[0]
            self.assertFalse(
                shortcut_path.resolve(strict=False).is_relative_to(
                    scope_paths["shortcut_root"].resolve(strict=False)
                )
            )
            self.assertIn("WARNING: shortcut output resolves outside the default shortcut root", stdout.getvalue())

    def test_script_expansion_preserves_powershell_variables_and_expands_braced_env(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "PwshApp"
            dst = Path(tmpdir) / "PwshApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v5.4.3.l2"
            identity, runtime, _raw_config, _warnings = load_runtime_config(module, version_dir)
            wrapper_content = runtime["bin"][0]["content"] + "\n${SystemRoot}\n"
            with mock.patch.dict(os.environ, {"SystemRoot": r"C:\Windows"}, clear=False):
                expansion = module.expand_text(wrapper_content, identity, module.ExpansionMode.SCRIPT)
            self.assertEqual(expansion.unresolved, [])
            self.assertIn("$ErrorActionPreference = 'Stop'", expansion.value)
            self.assertIn("$app = Join-Path $PSScriptRoot 'PwshApp.exe'", expansion.value)
            self.assertIn('& $app @args', expansion.value)
            self.assertIn(r"C:\Windows", expansion.value)

    def test_missing_variable_in_path_is_error_not_silent_success(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            src = FIXTURES / "BadPathApp"
            dst = Path(tmpdir) / "BadPathApp"
            shutil.copytree(src, dst)
            version_dir = dst / "v1.0.0.l1"
            identity, _ = resolve_identity(module, version_dir)
            with contextlib.redirect_stdout(io.StringIO()):
                result = module.add_to_path([r"${MISSING_VAR}"], identity, module.Scope.USER)
            self.assertFalse(result.ok)
            self.assertFalse(result.changed)
            self.assertTrue(any("unresolved variable" in err for err in result.errors))

    def test_missing_variable_in_shortcut_target_fails_step(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "ShortcutApp" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            identity, _ = resolve_identity(module, version_dir)
            with mock.patch.dict(os.environ, {"APPDATA": tmpdir, "USERPROFILE": tmpdir}, clear=False):
                scope_paths = module.compute_scope_paths(module.Scope.USER)
                with contextlib.redirect_stdout(io.StringIO()):
                    result = module.install_shortcuts(
                        [{"name": "Broken Shortcut", "targetPath": r"${MISSING_VAR}\App.exe"}],
                        identity,
                        scope_paths,
                    )
            self.assertFalse(result.ok)
            self.assertTrue(any("unresolved variable" in err for err in result.errors))

    def test_shortcut_creation_escapes_apostrophes_in_powershell_command(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = Path(tmpdir) / "ApostropheApp" / "v1.0.0.l1"
            version_dir.mkdir(parents=True)
            identity, _ = resolve_identity(module, version_dir)
            appdata = Path(tmpdir) / "O'Brien"
            appdata.mkdir(parents=True, exist_ok=True)
            with mock.patch.dict(os.environ, {"APPDATA": str(appdata), "USERPROFILE": tmpdir}, clear=False):
                scope_paths = module.compute_scope_paths(module.Scope.USER)
                captured = {}

                def fake_run(cmd, **kwargs):
                    captured["cmd"] = cmd

                    class Result:
                        returncode = 0
                        stderr = ""
                        stdout = ""

                    return Result()

                with mock.patch.object(module.subprocess, "run", side_effect=fake_run):
                    with contextlib.redirect_stdout(io.StringIO()):
                        result = module.install_shortcuts(
                            [{"name": "O'Brien Tool", "targetPath": r"C:\Tools\app.exe"}],
                            identity,
                            scope_paths,
                        )
            self.assertTrue(result.ok, msg=result.errors)
            self.assertIn("-NoProfile", captured["cmd"])
            self.assertIn("-NonInteractive", captured["cmd"])
            ps_command = captured["cmd"][-1]
            self.assertIn("O''Brien Tool.lnk", ps_command)
            self.assertIn("O''Brien", ps_command)

    def test_help_hides_bootstrap_only_python_flag(self) -> None:
        module = load_pkg_module()
        stdout = io.StringIO()
        with self.assertRaises(SystemExit) as cm:
            with contextlib.redirect_stdout(stdout):
                module.main(["--help"])
        self.assertEqual(cm.exception.code, 0)
        help_text = stdout.getvalue()
        self.assertNotIn("--python", help_text)

    def test_help_hides_removed_compatibility_flags(self) -> None:
        module = load_pkg_module()
        stdout = io.StringIO()
        with self.assertRaises(SystemExit) as cm:
            with contextlib.redirect_stdout(stdout):
                module.main(["--help"])
        self.assertEqual(cm.exception.code, 0)
        help_text = stdout.getvalue()
        self.assertNotIn("--no-autoupdate-config", help_text)
        self.assertNotIn("Compress", help_text)

    def test_help_extended_mentions_bootstrap_interpreter_selection(self) -> None:
        module = load_pkg_module()
        stdout = io.StringIO()
        with self.assertRaises(SystemExit) as cm:
            with contextlib.redirect_stdout(stdout):
                module.main(["--help-extended"])
        self.assertEqual(cm.exception.code, 0)
        help_text = stdout.getvalue()
        self.assertIn("Bootstrap interpreter selection", help_text)
        self.assertIn("--python <exe-or-command>", help_text)
        self.assertIn("PKG_PYTHON", help_text)

    def test_main_accepts_hidden_python_bootstrap_arg(self) -> None:
        module = load_pkg_module()
        with mock.patch.object(
            module,
            "install_package",
            return_value=module.ActionResult(ok=True, changed=False, exit_code=module.EXIT_SUCCESS),
        ) as install_mock:
            with contextlib.redirect_stdout(io.StringIO()):
                exit_code = module.main(["--python", sys.executable, "."])
        self.assertEqual(exit_code, module.EXIT_SUCCESS)
        install_mock.assert_called_once()

    def test_write_bytes_atomic_updates_wrapper_atomically(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "tool.cmd"
            module.write_bytes_atomic(path, b"@echo off\r\necho one\r\n")
            self.assertEqual(path.read_bytes(), b"@echo off\r\necho one\r\n")
            module.write_bytes_atomic(path, b"@echo off\r\necho two\r\n")
            self.assertEqual(path.read_bytes(), b"@echo off\r\necho two\r\n")
            temps = list(Path(tmpdir).glob(".*.tmp"))
            self.assertEqual(temps, [])


if __name__ == "__main__":
    unittest.main()
