from __future__ import annotations

import contextlib
import hashlib
import importlib.util
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import tomllib
import zipfile
from pathlib import Path
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ROOT / "src"
PKG_PY = SRC_ROOT / "pkg.py"
FIXTURES = ROOT / "tests" / "fixtures"


def load_pkg_module():
    spec = importlib.util.spec_from_file_location("pkg_under_test_cli", PKG_PY)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(spec.name, None)
    return module


@contextlib.contextmanager
def pushd(path: Path):
    cwd = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(cwd)


class PkgCliBehaviorTests(unittest.TestCase):
    maxDiff = None

    def run_main(self, module, args: list[str]) -> tuple[int, str]:
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            try:
                code = module.main(args)
            except SystemExit as exc:
                code = exc.code
        if code is None:
            code = 0
        self.assertIsInstance(code, int)
        return code, stdout.getvalue()

    def user_env(self, tmpdir: str) -> dict[str, str]:
        root = Path(tmpdir)
        return {
            "APPDATA": str(root / "AppData"),
            "USERPROFILE": str(root / "UserProfile"),
        }

    def machine_env(self, tmpdir: str) -> dict[str, str]:
        root = Path(tmpdir)
        return {
            "PROGRAMDATA": str(root / "ProgramData"),
            "SYSTEMDRIVE": str(root / "SystemDrive"),
        }

    def copy_fixture(self, tmpdir: str, name: str) -> Path:
        destination = Path(tmpdir) / name
        shutil.copytree(FIXTURES / name, destination)
        return destination

    def make_version_dir(self, tmpdir: str, package: str, version_dir_name: str = "v1.0.0.l1") -> Path:
        version_dir = Path(tmpdir) / package / version_dir_name
        version_dir.mkdir(parents=True)
        return version_dir

    def write_config(self, version_dir: Path, text: str) -> None:
        version_dir.joinpath("pkg.toml").write_text(textwrap.dedent(text).lstrip(), encoding="utf-8")

    def zip_bytes(self, entries: dict[str, str]) -> bytes:
        archive = io.BytesIO()
        with zipfile.ZipFile(archive, "w") as zip_file:
            for name, content in entries.items():
                zip_file.writestr(name, content)
        return archive.getvalue()

    def assert_documented_starter_config(
        self,
        text: str,
        *,
        name: str,
        version: str,
        local_version: int,
        only_portable: bool = False,
    ) -> None:
        nonblank_lines = [line.strip() for line in text.splitlines() if line.strip()]
        self.assertTrue(nonblank_lines, msg="Starter config should not be empty.")
        header = nonblank_lines[0]
        self.assertTrue(header.startswith("#"), msg="Starter config should begin with a comment header.")
        self.assertIn("pkg", header.lower(), msg="Starter config header should identify pkg as the generator.")
        self.assertTrue(
            any(token in header.lower() for token in ("generated", "auto-generated", "autogenerated")),
            msg="Starter config header should indicate that the file was generated.",
        )
        self.assertIn(f'name = "{name}"', text)
        self.assertIn(f'version = "{version}"', text)
        self.assertIn(f"localVersion = {local_version}", text)
        self.assertIn(f"only_portable = {str(only_portable).lower()}", text)
        self.assertIn("# [origin]", text)
        self.assertIn("# [[origin.versions]]", text)
        self.assertIn("# Multiple origin versions:", text)
        self.assertIn("#   1. omit top-level url/script above", text)
        self.assertIn("# Or use the package top-level version to select the current origin:", text)
        self.assertIn("#   2. define a [[origin.versions]] entry whose version matches", text)
        self.assertIn("#      the top-level package version above", text)
        for example_block in ("shortcut", "environment", "path", "bin"):
            self.assertIn(f"# [[{example_block}]]", text)

    def test_version_flag_reports_version(self) -> None:
        module = load_pkg_module()
        code, output = self.run_main(module, ["--version"])
        self.assertEqual(code, 0)
        self.assertIn(module.__version__, output)

    def test_short_help_hides_bootstrap_and_removed_flags(self) -> None:
        module = load_pkg_module()
        code, help_text = self.run_main(module, ["--help"])
        self.assertEqual(code, 0)
        self.assertIn("--action", help_text)
        self.assertNotIn("--python", help_text)
        self.assertNotIn("--no-autoupdate-config", help_text)
        self.assertNotIn("Compress", help_text)

    def test_extended_help_documents_bootstrap_interpreter_selection(self) -> None:
        module = load_pkg_module()
        code, help_text = self.run_main(module, ["--help-extended"])
        self.assertEqual(code, 0)
        self.assertIn("Bootstrap interpreter selection", help_text)
        self.assertIn("--python <exe-or-command>", help_text)
        self.assertIn("PKG_PYTHON", help_text)

    def test_hidden_python_arg_is_accepted_by_cli(self) -> None:
        module = load_pkg_module()
        with mock.patch.object(
            module,
            "install_package",
            return_value=module.ActionResult(ok=True, changed=False, exit_code=module.EXIT_SUCCESS),
        ) as install_mock:
            code, _output = self.run_main(module, ["--python", sys.executable, "."])
        self.assertEqual(code, module.EXIT_SUCCESS)
        install_mock.assert_called_once()

    def test_invalid_install_path_returns_user_error_and_banner(self) -> None:
        module = load_pkg_module()
        code, output = self.run_main(module, [str(ROOT / "does-not-exist")])
        self.assertEqual(code, module.EXIT_USER_ERROR)
        self.assertIn("Operation: Install", output)
        self.assertIn("Install failed.", output)

    def test_update_config_creates_documented_starter_file_when_missing(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"

            code, output = self.run_main(module, ["--action", "UpdateConfig", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            pkg_toml = version_dir / "pkg.toml"
            self.assertTrue(pkg_toml.exists())
            self.assert_documented_starter_config(
                pkg_toml.read_text(encoding="utf-8"),
                name="NoConfigApp",
                version="0.9.0",
                local_version=1,
            )

    def test_update_config_default_path_uses_caller_current_directory(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "DotApp")

            with pushd(version_dir):
                code, output = self.run_main(module, ["--action", "UpdateConfig"])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertTrue((version_dir / "pkg.toml").exists())

    def test_update_config_uses_the_only_version_directory_when_current_is_missing(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"

            code, output = self.run_main(module, ["--action", "UpdateConfig", str(package_root)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            pkg_toml = version_dir / "pkg.toml"
            self.assertTrue(pkg_toml.exists())
            self.assert_documented_starter_config(
                pkg_toml.read_text(encoding="utf-8"),
                name="NoConfigApp",
                version="0.9.0",
                local_version=1,
            )

    def test_update_config_rejects_an_ambiguous_package_root_without_current(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = Path(tmpdir) / "AmbiguousApp"
            (package_root / "v1.0.0.l1").mkdir(parents=True)
            (package_root / "v2.0.0.l1").mkdir()

            code, output = self.run_main(module, ["--action", "UpdateConfig", str(package_root)])

            self.assertEqual(code, module.EXIT_USER_ERROR, msg=output)
            self.assertIn("contains multiple version directories", output)

    def test_update_config_syncs_metadata_and_preserves_existing_content(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "MismatchApp")
            version_dir = package_root / "v2.0.0.l3"

            code, output = self.run_main(module, ["--action", "UpdateConfig", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            pkg_toml = version_dir / "pkg.toml"
            updated = pkg_toml.read_text(encoding="utf-8")
            backup = (version_dir / "pkg.toml.bak").read_text(encoding="utf-8")
            parsed = tomllib.loads(updated)

            self.assertEqual(parsed["name"], "MismatchApp")
            self.assertEqual(parsed["version"], "2.0.0")
            self.assertEqual(parsed["localVersion"], 3)
            self.assertIn("# Name is stale on purpose.", updated)
            self.assertIn('targetPath = "$App\\\\Mismatch.exe"', updated)
            self.assertIn('name = "MismatchApp-OLD"', backup)

    def test_update_config_syncs_metadata_without_validating_runtime_entries(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "BrokenWriteApp", "v1.0.0.l2")
            self.write_config(
                version_dir,
                """
                # Keep this comment
                name = "BrokenWriteApp-OLD"
                version = "0.9.0"
                localVersion = 7
                only_portable = false

                [[shortcut]]
                name = "Broken Shortcut"
                x_note = "preserve me"
                """,
            )

            code, output = self.run_main(module, ["--action", "UpdateConfig", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn("# Keep this comment", updated)
            self.assertIn('name = "BrokenWriteApp"', updated)
            self.assertIn('version = "1.0.0"', updated)
            self.assertIn("localVersion = 2", updated)
            self.assertIn('x_note = "preserve me"', updated)
            self.assertNotIn("targetPath", updated)

    def test_update_config_preserves_hash_inside_quoted_metadata_string(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "C#Tool")
            self.write_config(
                version_dir,
                """
                # Keep this comment
                name = "C#Tool-OLD"
                version = "0.9.0"
                localVersion = 9
                only_portable = false
                description = "preserve me"
                """,
            )

            code, output = self.run_main(module, ["--action", "UpdateConfig", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            parsed = tomllib.loads(updated)
            self.assertEqual(parsed["name"], "C#Tool")
            self.assertIn('name = "C#Tool"', updated)
            self.assertNotIn('"C#Tool"#Tool-OLD"', updated)

    def test_install_without_config_uses_defaults_without_writing_or_creating_bin(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertIn("using defaults without creating a file", output)
            self.assertFalse((version_dir / "pkg.toml").exists())
            self.assertFalse((Path(env["USERPROFILE"]) / "bin").exists())

    def test_install_uses_the_only_version_directory_when_current_is_missing(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "NoConfigApp")
            version_dir = package_root / "v0.9.0.l1"
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True) as junction_mock:
                    with mock.patch.object(
                        module,
                        "install_components",
                        return_value=module.StepResult(ok=True, changed=False),
                    ) as components_mock:
                        code, output = self.run_main(module, [str(package_root)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            junction_mock.assert_called_once()
            self.assertEqual(junction_mock.call_args.args[0].version_path, version_dir)
            components_mock.assert_called_once()

    def test_install_rejects_legacy_config_aliases_with_actionable_error(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "AliasApp")
            self.write_config(
                version_dir,
                """
                name = "AliasApp"
                version = "1.0.0"
                localVersion = 1

                ENV = [{ Name = "ALIAS_HOME", Value = "$App" }]
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("Unsupported legacy key 'ENV' in config. Use 'environment' instead.", output)

    def test_install_aborts_on_metadata_mismatch_before_mutations(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "MismatchApp")
            version_dir = package_root / "v2.0.0.l3"

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed") as junction_mock:
                    with mock.patch.object(module, "install_components") as components_mock:
                        code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            junction_mock.assert_not_called()
            components_mock.assert_not_called()
            self.assertIn("Configuration inconsistencies detected", output)
            self.assertIn('name = "MismatchApp-OLD"', (version_dir / "pkg.toml").read_text(encoding="utf-8"))
            self.assertFalse((version_dir / "pkg.toml.bak").exists())

    def test_install_with_fix_config_repairs_metadata_then_continues(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "MismatchApp")
            version_dir = package_root / "v2.0.0.l3"

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True) as junction_mock:
                    with mock.patch.object(
                        module,
                        "install_components",
                        return_value=module.StepResult(ok=True, changed=False),
                    ) as components_mock:
                        code, output = self.run_main(module, ["--fix-config", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            junction_mock.assert_called_once()
            components_mock.assert_called_once()
            self.assertIn("Configuration updated successfully.", output)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            backup = (version_dir / "pkg.toml.bak").read_text(encoding="utf-8")
            self.assertIn('name = "MismatchApp"', updated)
            self.assertIn('version = "2.0.0"', updated)
            self.assertIn("localVersion = 3", updated)
            self.assertIn('name = "MismatchApp-OLD"', backup)

    def test_install_with_fix_config_repairs_portable_flag_before_machine_scope_gate(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "MachineRepairApp")
            self.write_config(
                version_dir,
                """
                name = "MachineRepairApp"
                version = "1.0.0"
                localVersion = 1
                only_portable = true
                """,
            )

            with mock.patch.dict(os.environ, self.machine_env(tmpdir), clear=False):
                with mock.patch.object(module, "is_current_user_admin", return_value=True):
                    with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=module.StepResult(ok=True, changed=False),
                        ):
                            code, output = self.run_main(
                                module,
                                ["--scope", "Machine", "--fix-config", str(version_dir)],
                            )

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertIn("Configuration updated successfully.", output)
            self.assertNotIn("only_portable packages cannot be installed system-wide", output)
            updated = (version_dir / "pkg.toml").read_text(encoding="utf-8")
            self.assertIn("only_portable = false", updated)

    def test_shortcut_creation_failure_makes_install_fail(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ShortcutFailureApp")
            self.write_config(
                version_dir,
                r"""
                name = "ShortcutFailureApp"
                version = "1.0.0"
                localVersion = 1

                [[shortcut]]
                name = "Broken Shortcut"
                targetPath = "C:\\Tools\\missing.exe"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module, "create_shortcut", side_effect=RuntimeError("boom")):
                        code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertIn("Failed to create shortcut 'Broken Shortcut': boom", output)

    def test_unresolved_path_variable_makes_install_fail_before_registry_write(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            package_root = self.copy_fixture(tmpdir, "BadPathApp")
            version_dir = package_root / "v1.0.0.l1"

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertIn("unresolved variable", output)

    def test_unresolved_shortcut_variable_makes_install_fail_before_shortcut_creation(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ShortcutApp")
            self.write_config(
                version_dir,
                r"""
                name = "ShortcutApp"
                version = "1.0.0"
                localVersion = 1

                [[shortcut]]
                name = "Broken Shortcut"
                targetPath = "${MISSING_VAR}\\App.exe"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module, "create_shortcut") as create_shortcut_mock:
                        code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            create_shortcut_mock.assert_not_called()
            self.assertIn("unresolved variable", output)

    def test_bin_name_outside_default_root_is_allowed_but_warned(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "WarnBinApp")
            self.write_config(
                version_dir,
                """
                name = "WarnBinApp"
                version = "1.0.0"
                localVersion = 1

                [[bin]]
                name = "../outside.cmd"
                content = "@echo off\\r\\n"
                """,
            )
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(
                        module,
                        "ensure_bin_in_path",
                        return_value=module.StepResult(ok=True, changed=False),
                    ):
                        code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertTrue((Path(env["USERPROFILE"]) / "outside.cmd").exists())
            self.assertIn("WARNING: bin output resolves outside the default bin root", output)

    def test_shortcut_name_outside_default_root_is_allowed_but_warned(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "WarnShortcutApp")
            self.write_config(
                version_dir,
                r"""
                name = "WarnShortcutApp"
                version = "1.0.0"
                localVersion = 1

                [[shortcut]]
                name = "../outside"
                targetPath = "C:\\Tools\\tool.exe"
                """,
            )
            env = self.user_env(tmpdir)

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module, "create_shortcut") as create_shortcut_mock:
                        code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            shortcut_path = create_shortcut_mock.call_args.args[0]
            default_root = Path(env["APPDATA"]) / "Microsoft" / "Windows" / "Start Menu" / "opt"
            self.assertFalse(shortcut_path.resolve(strict=False).is_relative_to(default_root.resolve(strict=False)))
            self.assertIn("WARNING: shortcut output resolves outside the default shortcut root", output)

    def test_bin_wrapper_content_keeps_shell_variables_and_expands_braced_env(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "PwshScriptApp")
            self.write_config(
                version_dir,
                """
                name = "PwshScriptApp"
                version = "1.0.0"
                localVersion = 1

                [[bin]]
                name = "tool.ps1"
                content = '''
                $ErrorActionPreference = 'Stop'
                ${SystemRoot}
                $app = Join-Path $PSScriptRoot 'Tool.exe'
                & $app @args
                '''
                """,
            )
            env = self.user_env(tmpdir)
            env["SystemRoot"] = r"C:\Windows"

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(
                        module,
                        "ensure_bin_in_path",
                        return_value=module.StepResult(ok=True, changed=False),
                    ):
                        code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            written = (Path(env["USERPROFILE"]) / "bin" / "tool.ps1").read_text(encoding="utf-8")
            self.assertIn("$ErrorActionPreference = 'Stop'", written)
            self.assertIn(r"C:\Windows", written)
            self.assertIn("$app = Join-Path $PSScriptRoot 'Tool.exe'", written)
            self.assertIn("& $app @args", written)

    def test_install_updates_existing_wrapper_file(self) -> None:
        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "WrapperRepairApp")
            env = self.user_env(tmpdir)

            def write_wrapper_config(message: str) -> None:
                self.write_config(
                    version_dir,
                    f"""
                    name = "WrapperRepairApp"
                    version = "1.0.0"
                    localVersion = 1

                    [[bin]]
                    name = "tool.cmd"
                    content = "@echo off\\r\\necho {message}\\r\\n"
                    """,
                )

            with mock.patch.dict(os.environ, env, clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(
                        module,
                        "ensure_bin_in_path",
                        return_value=module.StepResult(ok=True, changed=False),
                    ):
                        write_wrapper_config("one")
                        first_code, first_output = self.run_main(module, [str(version_dir)])
                        write_wrapper_config("two")
                        second_code, second_output = self.run_main(module, [str(version_dir)])

            self.assertEqual(first_code, module.EXIT_SUCCESS, msg=first_output)
            self.assertEqual(second_code, module.EXIT_SUCCESS, msg=second_output)
            written = (Path(env["USERPROFILE"]) / "bin" / "tool.cmd").read_text(encoding="ascii")
            self.assertIn("echo two", written)
            self.assertNotIn("echo one", written)

    def test_install_rejects_top_level_download_url(self) -> None:
        """Install rejects the removed top-level downloadURL schema."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "OldDownloadApp")
            self.write_config(
                version_dir,
                """
                name = "OldDownloadApp"
                version = "1.0.0"
                localVersion = 1
                downloadURL = "https://example.invalid/app.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("Unsupported legacy key 'downloadURL'", output)

    def test_install_populates_missing_app_from_zip_origin_before_components(self) -> None:
        """Install downloads a zip origin into a missing App before installing components."""

        module = load_pkg_module()
        archive = self.zip_bytes({"tool/tool.exe": "payload"})
        checksum = hashlib.sha256(archive).hexdigest()

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ZipOriginApp")
            self.write_config(
                version_dir,
                f"""
                name = "ZipOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                checksum = "sha256:{checksum}"
                extractSubdir = "tool"
                """,
            )

            def assert_app_ready(*_args, **_kwargs):
                self.assertEqual((version_dir / "App" / "tool.exe").read_text(encoding="utf-8"), "payload")
                return module.StepResult(ok=True, changed=False)

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen", return_value=io.BytesIO(archive)) as urlopen_mock:
                        with mock.patch.object(module, "install_components", side_effect=assert_app_ready):
                            code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_called_once_with("https://example.invalid/tool.zip")
            self.assertIn("Verifying sha256 checksum", output)

    def test_install_skips_zip_origin_when_app_is_already_populated(self) -> None:
        """Install does not download origin when App already contains entries."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "SkipOriginApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "existing.txt").write_text("keep", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "SkipOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen") as urlopen_mock:
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=module.StepResult(ok=True, changed=False),
                        ):
                            code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_not_called()
            self.assertEqual((version_dir / "App" / "existing.txt").read_text(encoding="utf-8"), "keep")
            self.assertIn("App is already populated; skipping origin population", output)

    def test_install_selects_versioned_origin_matching_package_version(self) -> None:
        """Install uses the versioned origin entry matching the package version."""

        module = load_pkg_module()
        archive = self.zip_bytes({"selected.exe": "selected"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "SelectedOriginApp")
            self.write_config(
                version_dir,
                """
                name = "SelectedOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "0.9"
                url = "https://example.invalid/old.zip"

                [[origin.versions]]
                version = "1.0.0"
                url = "https://example.invalid/current.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen", return_value=io.BytesIO(archive)) as urlopen_mock:
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=module.StepResult(ok=True, changed=False),
                        ):
                            code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_called_once_with("https://example.invalid/current.zip")
            self.assertTrue((version_dir / "App" / "selected.exe").exists())

    def test_refresh_app_replaces_existing_app_from_zip_origin(self) -> None:
        """--refresh-app replaces existing App contents from a zip origin."""

        module = load_pkg_module()
        archive = self.zip_bytes({"new.exe": "new"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "RefreshOriginApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "old.exe").write_text("old", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "RefreshOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen", return_value=io.BytesIO(archive)):
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=module.StepResult(ok=True, changed=False),
                        ):
                            code, output = self.run_main(module, ["--refresh-app", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertEqual((version_dir / "App" / "new.exe").read_text(encoding="utf-8"), "new")
            self.assertFalse((version_dir / "App" / "old.exe").exists())

    def test_install_fails_when_selected_origin_version_has_no_source(self) -> None:
        """Install fails only when an incomplete versioned origin is used."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "IncompleteCurrentOriginApp")
            self.write_config(
                version_dir,
                """
                name = "IncompleteCurrentOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "1.0.0"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertIn("does not declare url or script", output)

    def test_checksum_mismatch_aborts_without_app_mutation(self) -> None:
        """Checksum mismatch fails before replacing an existing App directory."""

        module = load_pkg_module()
        archive = self.zip_bytes({"new.exe": "new"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ChecksumOriginApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "old.exe").write_text("old", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "ChecksumOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen", return_value=io.BytesIO(archive)):
                        code, output = self.run_main(module, ["--refresh-app", str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertEqual((version_dir / "App" / "old.exe").read_text(encoding="utf-8"), "old")
            self.assertIn("[origin].checksum did not match downloaded file", output)

    def test_unsafe_zip_path_aborts_without_app_mutation(self) -> None:
        """Unsafe archive paths are rejected before App is replaced."""

        module = load_pkg_module()
        archive = self.zip_bytes({"../escape.exe": "bad"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "UnsafeZipApp")
            (version_dir / "App").mkdir()
            (version_dir / "App" / "old.exe").write_text("old", encoding="utf-8")
            self.write_config(
                version_dir,
                """
                name = "UnsafeZipApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen", return_value=io.BytesIO(archive)):
                        code, output = self.run_main(module, ["--refresh-app", str(version_dir)])

            self.assertEqual(code, module.EXIT_MUTATION_ERROR)
            self.assertEqual((version_dir / "App" / "old.exe").read_text(encoding="utf-8"), "old")
            self.assertIn("unsafe path", output)

    def test_no_checksum_allows_install_with_warning(self) -> None:
        """--no-checksum skips configured checksum verification and warns."""

        module = load_pkg_module()
        archive = self.zip_bytes({"tool.exe": "payload"})

        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "NoChecksumOriginApp")
            self.write_config(
                version_dir,
                """
                name = "NoChecksumOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.urllib.request, "urlopen", return_value=io.BytesIO(archive)):
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=module.StepResult(ok=True, changed=False),
                        ):
                            code, output = self.run_main(module, ["--no-checksum", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertTrue((version_dir / "App" / "tool.exe").exists())
            self.assertIn("WARNING: Checksum verification skipped", output)

    def test_script_origin_receives_payload_and_working_directory(self) -> None:
        """Script origin receives enriched JSON on stdin and runs from the script directory."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "ScriptOriginApp")
            script_dir = version_dir / "scripts"
            script_dir.mkdir()
            script_path = script_dir / "populate.cmd"
            script_path.write_text("@echo off\r\n", encoding="ascii")
            self.write_config(
                version_dir,
                """
                name = "ScriptOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                script = "scripts/populate.cmd"
                """,
            )

            def run_script(*_args, **kwargs):
                payload = json.loads(kwargs["input"])
                self.assertEqual(payload["identity"]["name"], "ScriptOriginApp")
                self.assertNotIn("version", payload["config"]["origin"])
                self.assertEqual(Path(payload["PkgVars"]["App"]).resolve(), (version_dir / "App").resolve())
                self.assertEqual(Path(kwargs["cwd"]).resolve(), script_dir.resolve())
                app_dir = version_dir / "App"
                app_dir.mkdir()
                (app_dir / "created.txt").write_text("ok", encoding="utf-8")
                return subprocess.CompletedProcess(args=[], returncode=0, stdout="", stderr="")

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=True):
                    with mock.patch.object(module.subprocess, "run", side_effect=run_script) as run_mock:
                        with mock.patch.object(
                            module,
                            "install_components",
                            return_value=module.StepResult(ok=True, changed=False),
                        ):
                            code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            run_mock.assert_called_once()
            self.assertTrue((version_dir / "App" / "created.txt").exists())

    def test_health_check_accepts_valid_origin_history(self) -> None:
        """HealthCheck validates origin history without downloading or installing."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "HealthyOriginApp")
            script_dir = version_dir / "scripts"
            script_dir.mkdir()
            (script_dir / "populate.cmd").write_text("@echo off\r\n", encoding="ascii")
            self.write_config(
                version_dir,
                """
                name = "HealthyOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "0.9"
                url = "https://example.invalid/old.zip"

                [[origin.versions]]
                version = "1.0.0"
                script = "scripts/populate.cmd"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module.urllib.request, "urlopen") as urlopen_mock:
                    code, output = self.run_main(module, ["--action", "HealthCheck", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_not_called()
            self.assertIn("Health check passed.", output)

    def test_health_check_accepts_origin_history_without_sources(self) -> None:
        """HealthCheck accepts version-only origin history entries."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "VersionOnlyOriginApp")
            self.write_config(
                version_dir,
                """
                name = "VersionOnlyOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "0.9"

                [[origin.versions]]
                version = "1.0.0"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["--action", "HealthCheck", str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            self.assertIn("Health check passed.", output)

    def test_health_check_rejects_duplicate_origin_history_versions(self) -> None:
        """HealthCheck reports duplicate versioned origin entries."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "DuplicateOriginApp")
            self.write_config(
                version_dir,
                """
                name = "DuplicateOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "1.0"
                url = "https://example.invalid/one.zip"

                [[origin.versions]]
                version = "1.0"
                url = "https://example.invalid/two.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["--action", "HealthCheck", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("duplicate version: 1.0", output)

    def test_health_check_rejects_missing_package_version_origin_history(self) -> None:
        """HealthCheck reports origin history that lacks the package version."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "MissingSelectedOriginApp")
            self.write_config(
                version_dir,
                """
                name = "MissingSelectedOriginApp"
                version = "1.0.0"
                localVersion = 1

                [[origin.versions]]
                version = "2.0"
                url = "https://example.invalid/one.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["--action", "HealthCheck", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("[[origin.versions]] must contain an entry matching top-level version", output)

    def test_health_check_rejects_top_level_origin_version(self) -> None:
        """HealthCheck rejects removed top-level [origin].version syntax."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "OldSelectorOriginApp")
            self.write_config(
                version_dir,
                """
                name = "OldSelectorOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                version = "1.0.0"

                [[origin.versions]]
                version = "1.0.0"
                url = "https://example.invalid/one.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["--action", "HealthCheck", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("Unknown key 'version' in origin", output)

    def test_health_check_rejects_bad_origin_script_reference(self) -> None:
        """HealthCheck reports package-local script reference problems."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "BadScriptOriginApp")
            self.write_config(
                version_dir,
                """
                name = "BadScriptOriginApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                script = "scripts/missing.cmd"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                code, output = self.run_main(module, ["--action", "HealthCheck", str(version_dir)])

            self.assertEqual(code, module.EXIT_USER_ERROR)
            self.assertIn("[origin].script was not found", output)

    def test_newer_current_skip_also_skips_origin_population(self) -> None:
        """A preserved newer current skips origin population and component install."""

        module = load_pkg_module()
        with tempfile.TemporaryDirectory() as tmpdir:
            version_dir = self.make_version_dir(tmpdir, "NewerCurrentApp")
            self.write_config(
                version_dir,
                """
                name = "NewerCurrentApp"
                version = "1.0.0"
                localVersion = 1

                [origin]
                url = "https://example.invalid/tool.zip"
                """,
            )

            with mock.patch.dict(os.environ, self.user_env(tmpdir), clear=False):
                with mock.patch.object(module, "update_current_junction_if_needed", return_value=False):
                    with mock.patch.object(module.urllib.request, "urlopen") as urlopen_mock:
                        with mock.patch.object(module, "install_components") as install_components_mock:
                            code, output = self.run_main(module, [str(version_dir)])

            self.assertEqual(code, module.EXIT_SUCCESS, msg=output)
            urlopen_mock.assert_not_called()
            install_components_mock.assert_not_called()


if __name__ == "__main__":
    unittest.main()
