@echo off
setlocal EnableExtensions EnableDelayedExpansion

rem Parse the target first; all remaining tokens are optional name/value pairs.
if "%~1"=="" goto :usage
if /i "%~1"=="--help" goto :usage
if /i "%~1"=="-h" goto :usage

set "target="
set "shim_name="
set "shim_type=cli"
set "elevate=false"
set "forward_arguments=true"
set "working_dir="

set /a argument_count=0
for %%A in (%*) do (
  set /a argument_count+=1
  if !argument_count! EQU 1 (
    set "target=%%~A"
  ) else (
    set "option=%%~A"
    if defined pending_option (
      if /i "!pending_option!"=="name" set "shim_name=!option!"
      if /i "!pending_option!"=="type" set "shim_type=!option!"
      if /i "!pending_option!"=="elevate" set "elevate=!option!"
      if /i "!pending_option!"=="forward_arguments" set "forward_arguments=!option!"
      if /i "!pending_option!"=="working_dir" set "working_dir=!option!"
      set "pending_option="
    ) else (
      if /i "!option!"=="--name" set "pending_option=name"
      if /i "!option!"=="--type" set "pending_option=type"
      if /i "!option!"=="--elevate" set "pending_option=elevate"
      if /i "!option!"=="--forward-arguments" set "pending_option=forward_arguments"
      if /i "!option!"=="--working-dir" set "pending_option=working_dir"
      if not defined pending_option (
        echo error: unknown option "!option!".
        set "parse_error=1"
      )
    )
  )
)

rem Reject a dangling option before deriving output paths or copying files.
if defined pending_option (
  echo error: --!pending_option! requires a value.
  set "parse_error=1"
)
if defined parse_error goto :usage_error

:validate
rem Convert defaults and option text into values written to the TOML companion file.
if not defined shim_name for %%I in ("%target%") do set "shim_name=%%~nI"
if not defined shim_name set "shim_name=shim"
if /i "%shim_type%"=="cli" set "launcher=shim-console.exe"
if /i "%shim_type%"=="gui" set "launcher=shim-gui.exe"
if not defined launcher (
  echo error: --type must be cli or gui.
  exit /b 1
)
if /i not "%elevate%"=="true" if /i not "%elevate%"=="false" (
  echo error: --elevate must be true or false.
  exit /b 1
)
if /i not "%forward_arguments%"=="true" if /i not "%forward_arguments%"=="false" (
  echo error: --forward-arguments must be true or false.
  exit /b 1
)

set "output=%CD%\%shim_name%.exe"
set "config=%CD%\%shim_name%.config.toml"
rem Never overwrite an existing launcher or configuration without an explicit
rem manual removal by the caller.
if exist "%output%" (
  echo error: "%output%" already exists.
  exit /b 1
)
if exist "%config%" (
  echo error: "%config%" already exists.
  exit /b 1
)
if not exist "%~dp0%launcher%" (
  echo error: "%launcher%" was not found beside this script.
  exit /b 1
)

setlocal EnableDelayedExpansion
rem Escape the two characters that can terminate a TOML basic string.
set "toml_target=!target:\=\\!"
set "toml_target=!toml_target:"=\"!"
set "toml_working_dir=!working_dir:\=\\!"
set "toml_working_dir=!toml_working_dir:"=\"!"

copy /b /y "%~dp0%launcher%" "%output%" >nul || exit /b 1
rem Keep the generated configuration self-explanatory so it can be edited after
rem creation without consulting the repository documentation.
(
  echo # Generated by make-shim.cmd. Edit this file to customize the launcher.
  echo # The target may use inherited environment variables, for example %%LOCALAPPDATA%%\Tool\tool.exe.
  echo target = "!toml_target!"
  echo.
  echo # Forward arguments supplied to this shim after configured arguments.
  echo forward_arguments = %forward_arguments%
  echo.
  echo # Request UAC elevation before starting the target.
  echo elevate = %elevate%
  echo.
  echo # Use the directory containing target as its working directory when true.
  echo # When false, target inherits the directory from which this shim was launched.
  echo target_dir_as_working_dir = false
  if defined working_dir echo working_dir = "!toml_working_dir!"
  echo.
  echo # Add one or more fixed arguments. They are placed before caller arguments.
  echo # [[argument]]
  echo # value = "--example"
  echo.
  echo # Set child-only environment variables. Do not also list a name below.
  echo # [environment]
  echo # EXAMPLE_SETTING = "value"
  echo.
  echo # Remove inherited environment variables from the child process.
  echo # remove_environment = ["VIRTUAL_ENV"]
  echo.
  echo # Add directories to the beginning of the child PATH. Relative paths are
  echo # resolved from this configuration file's directory.
  echo # path_prepend = ["tools"]
) > "%config%"

echo Created "%output%" and "%config%".
exit /b 0

:usage_error
exit /b 1

:usage
echo Usage: %~nx0 "TARGET" [options]
echo.
echo Options:
echo   --name=NAME                 Output name, without .exe ^(default: target basename^)
echo   --type=cli^|gui              Launcher type ^(default: cli^)
echo   --elevate=true^|false        Request UAC elevation ^(default: false^)
echo   --forward-arguments=true^|false  Forward caller arguments ^(default: true^)
echo   --working-dir=PATH           Target working directory
echo.
echo The generated .config.toml documents fixed arguments and environment options.
exit /b 1
